### ISSUE TITLE
downloadable topmed dbsnp file for hg19

### ISSUE THREAD

**Issue by raungar** [brentp/slivar#103]
Hi-

Using your slivar tool has been wonderful and super helpful! I am wanting to annotate my VCFs in hg19 using TOPMed and gnomAD, but it seems the only linked hg19 files for annotations are for gnomAD. For TOPMed the only linked file for slivar is topmed.hg38.dbsnp.151.zip.

I imagine there are many people using your tool who would be interested in the hg19 version of this file, which is why I am posting an issue. I would find it really useful to have the file topmed.hg19.dbsnp.zip!

Thanks so much!
Rachel

**Comment by brentp** [comment]
Hi Rachel, glad to hear the tool is useful!
slivar has a command: `slivar make-gnotate` that will allow you to create your own gnotate file(s).
You'll need the topmed/dbsnp vcf in hg19 of course but then it should be a single command to create your own zip (gnotate) file.

Happy to help if you have any troubles. I prefer to support the tool rather than try to add every possible zip file because users often want different columns, different builds, etc. and the number of possibilities is unmanageable.
-B

**Comment by raungar** [comment]
That makes total sense! Thanks so much!

**Comment by raungar** [comment]
Hi-

I downloaded the topmed data, lifted over to hg19 using picard, and the
used make-gnotate to make this file! I'm responding via email (rather than
github) so I can attach this file in case it could be helpful to provide
for others

Thanks,
Rachel
 topmed_hg19.zip
<https://drive.google.com/file/d/1DXG_b8oqO2_zDBhDespWkBk6x0wlyP_j/view?usp=drive_web>

-Rachel

**Comment by brentp** [comment]
thanks Rachel, perhaps we could support this type of contribution by keeping a list of recipes (bash scripts or other) to make such zip files.

**Comment by raungar** [comment]
Sure!
Step 1. Download topmed and hg19.fa and then liftover
(topmed we already had, FA downloaded from [here](https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.fa.gz))
```
topmed_hg38="/path/freeze8.pass_only.phased.mesa_1319samples.maf01.biallelic.vcf.gz"
topmed_hg19="topmed_hg19.vcf.gz"
reject="REJECT_topmed_hg19.vcf.gz"
hg19_fa="/path/hg19.fa"
chain="hg38ToHg19.over.chain.gz"
picard LiftoverVcf I=$topmed_hg38 O=$topmed_hg19 CHAIN=$chain REJECT=$reject RECOVER_SWAPPED_REF_ALT=true R=$hg19_fa`
```

Step 2: run make-gnotate
 ```
               slivar make-gnotate \
                        --field AF:topmed_popmax_af \
                        --field AC:topmed_AC \
                        --prefix $my_prefix \
                        $topmed_hg19
```

**Comment by brentp** [comment]
thanks. I'll bookmark this and maybe create a collection of them.
