### ISSUE TITLE
slivar tsv and VEP canonical

### ISSUE THREAD

**Issue by Madelinehazel** [brentp/slivar#106]
Hi @brentp,

Is it possible for slivar to allow VEP's canonical flag in the CSQ field when exporting to tsv? E.g. gene_impact_transcript_Gene_CANONICAL_EXON_HGVSc_HGVSp_Protein_position_Consequence_PolyPhen_SIFT

Thanks,
Madeline

**Comment by brentp** [comment]
Hi, you can get other CSQ columns with `--csq-column` argument to `slivar tsv`
