### ISSUE TITLE
Gnotation Files hg38

### ISSUE THREAD

**Issue by jainy** [brentp/slivar#107]
Hi Brent,

I see that spliceai scores available are for hg37. It will be great if you provide for the hg38 version as well. Thank you!

Best,
Jainy

**Comment by brentp** [comment]
Hi Jainy, since it's folly for me to try to keep up with all possible builds and annotations, `slivar make-gnotate` is available so you can make your own gnotate/zip file for any VCF. I think the spliceAI would require some preprocessing (I made a new field that was the max of the 4 scores, I think). I'm happy to help with any difficulties you encounter using `make-gnotate`.

**Comment by jainy** [comment]
Thank you for the quick reply and pointers, Brent! I added the max of the 4 scores to the vcf and ran `make-gnotate`. It worked fine.

**Comment by brentp** [comment]
Excellent! Glad to hear it.

**Comment by lacek** [comment]
In SpliceAI v1.3 `spliceai_scores.masked.snv.hg38.vcf.gz`, some variants were duplicated with different max scores. Would you mind sharing how these should be dealt with in preprocessing after taking max of the 4 values in a row?

For the example below, would slivar give 0.02 or 0.09 or both for 12-121527653-C-G?

```tsv
12	121527653	.	C	A	.	.	SpliceAI=A|KDM2B|0.00|0.00|0.00|0.00|-3|-27|-3|39
12	121527653	.	C	A	.	.	SpliceAI=A|KDM2B|0.03|0.00|0.00|0.00|-3|-27|39|7
12	121527653	.	C	G	.	.	SpliceAI=G|KDM2B|0.02|0.00|0.00|0.00|-3|-9|-3|7
12	121527653	.	C	G	.	.	SpliceAI=G|KDM2B|0.09|0.00|0.00|0.00|-3|-1|39|7
12	121527653	.	C	T	.	.	SpliceAI=T|KDM2B|0.00|0.00|0.00|0.00|-3|-1|-3|0
12	121527653	.	C	T	.	.	SpliceAI=T|KDM2B|0.00|0.00|0.00|0.00|-3|-9|-3|39
```

**Comment by brentp** [comment]
I looked over the code and it looks like both values will be stored and likely only the first (after unstable sort, so either could be first) will be reported on annotation, so if you want to control this, you'd have to collapse records like these yourself before sending to make-gnotate.
