### ISSUE TITLE
slivar tsv: change --csq output delimiter for csq columns

### ISSUE THREAD

**Issue by zihhuafang** [brentp/slivar#109]
Hi @brentp:

Is it possible to change slivar tsv --csq output delimiter for the CSQ columns?
Currently, the aggregated info (one column) from CSQ fileds is "/" separated.
I would like to export the CSQ fields with another delimiter.

Thanks in advance.
Zih-Hua

**Comment by brentp** [comment]
Hi, sorry for the delay, I missed this. It's currently not possible. I think it's simple enough to post-process the tsv output to change that, rather than adding complexity to slivar, what do you think?

**Comment by zihhuafang** [comment]
Hi Brent,

I do agree that post-process tsv is feasible, which is what I am doing now. It's not a necessary feature for sure.

Just that it is a lot of grouping and cleaning of the dataframe due to delimiter. One example would be exon number (e.g. 3/10) or amino acid change (R/V) from VEP, which use '/' as well. I need to group by missense, synonymous and UTR variants and organise the split csq_column accordingly. Nevertheless, it's not something that the end-user can't handle.

Thanks for the thought!
