### ISSUE TITLE
slivar tsv

### ISSUE THREAD

**Issue by sprakashUTH** [brentp/slivar#112]
I used slivar_expr to filter a vcf and am having issues when I try to reformat using tsv. What am I doing wrong?

1. ./slivar expr --vcf $vcf --ped $ped --pass-only -g gnomad.hg38.v2.zip -g topmed.hg38.dbsnp.151.zip --info 'INFO.impactful && INFO.gnomad_popmax_af < 0.0001 && variant.FILTER == "PASS" && variant.ALT[0] != "*" && INFO.topmed_af < 0.0001 && INFO.highest_impact_order <= ImpactOrder.disruptive_inframe_deletion' --js slivar-functions.js > $cohort.highest.vcf

2. ./slivar tsv -s slivar_expr -i gnomad_popmax_af -i gnomad_popmax_af_filter -i gnomad_nhomalt -c ANN -g pli.lookup -g clinvar_gene_desc.txt -p $ped $cohort.highest.vcf > $cohort.highest.tsv

> slivar version: 0.2.1 ceb97b26cd39d341dd7aa96ddb42239692df5b50
vcf.nim(157)             get
Error: unhandled exception: slivar_expr not found in header [KeyError]

**Comment by brentp** [comment]
Hi, slivar tsv mostly works on output from trios. 
But, in your tsv command, you show `-s slivar_expr` in order to use that, you would have to have used `--trio 'slivar_expr:kid.het ...` in the first command.

**Comment by sprakashUTH** [comment]
I solved that issue by using the "dominant" flag in the first command. How do I get the Amino_acid change of the variant to export to the tsv?

**Comment by brentp** [comment]
hi, you can use `--csq-column $column` where $column matches the name in the description for ANN or BCSQ
