### ISSUE TITLE
question about the difference between comphet_side and slivar_comphet

### ISSUE THREAD

**Issue by hust-yyan** [brentp/slivar#114]
Hello, I used slivar expr for analysis and then used slivar compound-hets for analysis. The following two contents were added to INFO in the VCFs file. What are the differences between the two?
![image](https://user-images.githubusercontent.com/54279739/148474940-b0a96535-2cee-4c29-b327-b24f9cf1aed2.png)

**Comment by brentp** [comment]
Hi, comphet_side is per-variant. That means that the kid and exactly 1 parent were heterozygous at that site.
slivar_comphet means that slivar did the phasing and found a pair of (comphet_side) variants on different haplotypes.

**Comment by brentp** [comment]
... so you can look at `slivar_cophet` and ignore `comphet_side`.
