### ISSUE TITLE
Error: unhandled exception: SyntaxError

### ISSUE THREAD

**Issue by luceamso** [brentp/slivar#116]
Hi Brent, 

Thank you for sharing Slivar with the field. This is very useful.

While running Slivar on my VCF file to filter variants, I encountered the following issues and would like to ask you for help. The VCF file (cs_affected_fam.vcf.gz) was annotated with ANNOVAR databases including several customized ones, for instance, “gnomAD_r2.1.1_merged_all” and “bravo_freeze8” etc. (I have attached the list of databases used for ANNOVAR annotation). After several testings, I noticed that Slivar outputs the error when I tried to filter variants based on the “gnomAD_r2.1.1_merged_all” but it works fine with “bravo_freeze8“ which is another customized database (please see below).
I would be grateful if you could look into this issue when you have a chance.

Thanks again.
Seoon

<img width="568" alt="gnomad" src="https://user-images.githubusercontent.com/92145521/151112455-941c7467-d9b5-432e-878e-e0991b8f4592.png">
<img width="684" alt="brovo" src="https://user-images.githubusercontent.com/92145521/151112446-29e40fbc-8e82-474c-9168-421da1b29e22.png">

[INFO.txt](https://github.com/brentp/slivar/files/7939286/INFO.txt)

**Comment by luceamso** [comment]
> Hi, Brent. Thanks for useful tool.
> 
> I would like to ask you for help on the issue.
> 
> `slivar expr \
> 
> > --js slivar-functions.js 
> > --vcf cs_affected_fam.vcf.gz 
> > --ped cs_fam1.ped 
> > --info "INFO.gnomAD_r2.1.1_merged_all < 0.001" 
> > --pass-only
> > slivar version: 0.2.7 [71af7d1](https://github.com/brentp/slivar/commit/71af7d12881ae0590c6d2a97ef2b282cc93fe7c6)
> > [slivar] 5 samples matched in VCF and PED to be evaluated
> > [slivar tsv] warning! didn't find ANN in header in cs_affected_fam.vcf.gz trying other fields
> > [slivar tsv] warning! didn't find ANN in header in cs_affected_fam.vcf.gz trying other fields
> > [slivar tsv] warning! didn't find CSQ in header in cs_affected_fam.vcf.gz trying other fields
> > [slivar tsv] warning! didn't find CSQ in header in cs_affected_fam.vcf.gz trying other fields
> > [slivar tsv] warning! didn't find BCSQ in header in cs_affected_fam.vcf.gz trying other fields
> > [slivar tsv] warning! didn't find BCSQ in header in cs_affected_fam.vcf.gz trying other fields
> > duko.nim(71)             compile
> > Error: unhandled exception: SyntaxError: unterminated statement (line 1)
> > expression was:'INFO.gnomAD_r2.1.1_merged_all < 0.001' [ValueError]`
> 
> I ran slivar expr for filtering. The vcf file has been annotated with customed and public databases. I tried to select candidates using gnomAD.2.1.1 merged_all which is one of customed databases. But i got that issue. So i used bravo_freeze8 which is a different customed database to check if the same problem occurs. However, slivar worked well with no any problems when using bravo_freeze8.
> 
> Could you please check what the problem is? I attaced a file that it printed out INFO filed to help. [INFO.txt](https://github.com/brentp/slivar/files/7939070/INFO.txt)
> 
> Thanks!

**Comment by brentp** [comment]
Hi, the problem is the attribute: `gnomAD_r2.1.1_merged_all`. You can't use the javascript `.` notation on that, but you can use, for example:
```
--info INFO['gnomAD_r2.1.1_merged_all'] < 0.001
```
this how you can access attributes with '.' or spaces in javascript.
