### ISSUE TITLE
Variant-Level labelling

### ISSUE THREAD

**Issue by MattWellie** [brentp/slivar#121]
(There may be something related to this in the documentation, but I've not been able to find it)

I would like to use Slivar for a classification workflow. There will be a first-pass assigning categories to variants based principally consequence and frequency annotations. There will be a number of different filters applied, each for a different 'class', which will result in variant labelling. 

So far I can implement this using:

- Slivar to apply `info` filters, and saving those variant positions in a BED
- Reheadering the VCF to include a new flag definition
- BCFTools annotate to apply the flag to specific variants

Is there a way using only Slivar to apply variant-level labels to variants, in the same way that the family/group/sample expressions are able to apply the results to the VCF output? Those expressions are technically usable, but they add every sample's ID into the resulting field if the filter only includes variant-level attributes.

e.g.
I would like to be able to use

```
slivar \
  -v VCF \
  -j JS \
  -p PED \
  --info '<basic filters>' \
  --variant-expr 'ClassA:passes_class_a(variant)' \
  --variant-expr 'ClassB:passes_class_b(variant)'
```

and a flag "ClassA" or "ClassB" would be annotated into the INFO of relevant variants.

**Comment by brentp** [comment]
Hi, that's not possible currently. I see the utility, but it would be a lot of work to add. I'll have a look at the code in the next few weeks, but I suggest to find another way to do it.
