### ISSUE TITLE
how can I extract \xb3 in slivar?

### ISSUE THREAD

**Issue by luceamso** [brentp/slivar#128]
Hi,
I'm very appreciated with your help and thanks for wonderful tool.
I tried several times to extract variants with annotation containing "\x3b" but have failed.
I confirmed "ncRNA_exonic\x3bsplicing" annotation in subset vcf file and used 
`--info "INFO['Func.refGeneWithVer'] == 'ncRNA_exonic\\x3bsplicing'"` 
but it's not worked.  
I would like to ask for help on this.
Sorry for asking a very basic question.

**Comment by brentp** [comment]
Hi, this is hard because your shell will interpret the `\\` in some cases. I would try:
```
--info 'INFO["Func.refGeneWithVer"] == "ncRNA_exonic\x3bsplicing"'
```
with outer `'` and inner `"` and various escape patterns of that.

You could also try:
```
'INFO["Func.refGeneWithVer"].match("^ncRNA_exonic")
```
and mofify the regex to get the exact match that you want.

**Comment by brentp** [comment]
can you share a VCF with a single record that should match but doesn't?

**Comment by luceamso** [comment]
sure, thanks for your time.

[single.txt](https://github.com/brentp/slivar/files/8640233/single.txt)

**Comment by brentp** [comment]
can you share one with the header?

**Comment by luceamso** [comment]
added the header, thank you!

[single.txt](https://github.com/brentp/slivar/files/8640265/single.txt)

**Comment by brentp** [comment]
I was able to use this:
```
 --info 'INFO["Func.refGeneWithVer"].match("^ncRNA") != null'
```

**Comment by luceamso** [comment]
I extracted the variant what I want as modified the code you provided.
Thank you so much!
