### ISSUE TITLE
  SIGSEGV: Illegal storage access. (Attempt to read from nil?)

### ISSUE THREAD

**Issue by zeliasoo** [brentp/slivar#130]
While trying to run slivar v0.2.4, we encountered the following error: 

Command error:
  > slivar version: 0.2.4 d64b67c51ab4f3323e08caf65f2bb9aeb3aab285
  [slivar] no ped file specified, not able to determine family relationships.
  SIGSEGV: Illegal storage access. (Attempt to read from nil?)

We run slivar in our bioinformatic pipeline and everything goes smoothly, but filtered list to tsv part failed and we can't solve it. Can anyone help us solve this?

**Comment by brentp** [comment]
Hi, can you try with the latest version (v0.2.7) of slivar and see if that resolves it? If not, we can debug further if you can send the full command that you ran.

**Comment by brentp** [comment]
Hi, this is because of the way that you ran bcftools CSQ the `@17397477` is a reference to another entry. You'll need to run bcftool csq something like this:
```
bcftools csq -s - --ncsq 40 -g $gff -l -f $fasta $vcf -O u -o $vcf_with_csq
```
