### ISSUE TITLE
Finding de novo/autosomal recessive structural variants using slivar

### ISSUE THREAD

**Issue by prasundutta87** [brentp/slivar#132]
Hi

I am attempting to use slivar for finding de novo/autosomal recessive SVs for rare disease. I have a trio VCF file that I generated using sniffles2. I have already pre-filtered my set of variants by my own algorithm/workflow. I was having a look at the javascript file that defines the rules for performing mode of inheritance filtering. Since its a SV VCF file, I don't have some FORMAT field tags such as DP and AD. Do I just need to edit the javascript file and that will be it? I will replace some of the tags there and use it instead to filter SVs using the slivar program.

Regards,
Prasun

**Comment by brentp** [comment]
Yes, you can edit the javascript file and otherwise follow the example here: https://github.com/brentp/slivar/wiki/rare-disease

For snps/indels, Allele balance (AB) is very helpful for filtering, but will likely not work the same way for SVs, so you can use your own fields and remove those checks.

**Comment by prasundutta87** [comment]
Hi @brentp ..Thanks a lot for this!

**Comment by poddarharsh15** [comment]
> Hi @brentp ..Thanks a lot for this!

Hi @prasundutta87,
Sorry to reopen the issue again, but I was wondering if you were able to successfully run slivar on VCF files with trio samples [SVs] and finding the inheritance? I have a similar dataset, but with WES data. Could you please share any suggestions or ideas that might help? 

Thanks!
