### ISSUE TITLE
query about PED and trio VCF

### ISSUE THREAD

**Issue by prasundutta87** [brentp/slivar#134]
Hi,

I have trio VCF for structural variants. The sequence of my samples in the VCF is Father, Mother. Proband. Does this sequence affect slivar results? I have seen slivar function in the form of kid, mom, dad.

I don't have a ped file. Do you have any recommendation on how to create one? Is vcftools okay to use like this:

`vcftools --vcf <input_vcf> --out ped --plink
`

Regards,
Prasun

**Comment by brentp** [comment]
you can just make text pedfile like this:
```
#family_id sample_id paternal_id maternal_id sex phenotype
1                kid_id        dad_id       mom_id        2    2
1                dad_id       0               0                   1     1
1                mom_id     0               0                   2      1
```
replacing `mom_id`, `dad_id`, and `kid_id` with the sample names in the VCF. Once you have this pedigree file, then the order of the samples doesn't matter, it just infers mom, dad and kid.

**Comment by prasundutta87** [comment]
Thanks @brentp !
