### ISSUE TITLE
missing null frequency variants

### ISSUE THREAD

**Issue by luceamso** [brentp/slivar#136]
hi, Brent

I use "gnomAD_r2.1.1_merged_all" as one of the info attributes. It's working well because you told me how to apply this before. But I realized that null frequency is not recognized. Filtering by numbers works just fine.
I've tried several things, but nothing worked. Below are what I've tried:
```
--info "INFO['gnomAD_r2.1.1_merged_all'] == '.'"
instead of '." : '[.]', ['.'], "\\.", "\."
--info 'INFO["gnomAD_r2.1.1_merged_all"] == "."'
instead of '." : "[.]", ["."], "\\.", "\."
```

I would like to ask for help on this.

**Comment by brentp** [comment]
What does the VCF header look like for this field?

**Comment by luceamso** [comment]
oh, it's float.
I was confused by looking at the other field.
But why is the MQ field not recognized?
I had this error:
[slivar] error evaluating info expression (this can happen if a field is missing):
error from duktape: unknown attribute:MQ for expression:INFO.MQ > 40
and the field looks like:
##INFO=<ID=MQ,Number=1,Type=Float,Description="RMS Mapping Quality">
