### ISSUE TITLE
gnotate: converting BED to VCF

### ISSUE THREAD

**Issue by wwgordon** [brentp/slivar#144]
Hi Brent,

I'm working on setting up a slivar pipeline with @jxchong; we have a number of annotation files that are bed formatted rather than vcf/bcf. Do you have a recommended tool for conversion? plink perhaps?

Thanks,
William

**Comment by brentp** [comment]
Hi William (and Jessica), is the data of sequence-resolved variants? are there millions of variants? If so, then it makes sense to use gnotate. In that case, you'd have to write a script in python to do that. I have an example doing this for CADD (with another tool you might consider) [here](https://github.com/brentp/echtvar/tree/main/examples/cadd)

If you have few sites or not variants with REF and ALT, then just use [vcfanno](https://github.com/brentp/vcfanno).

**Comment by wwgordon** [comment]
Closing this as we have been successful in incorporating bed files, thanks!
