### ISSUE TITLE
slivar expr : unaffected patients not selected

### ISSUE THREAD

**Issue by gael-millot** [brentp/slivar#145]
Hi.

May be not an issue.
Using the attached files, when I use:
--family-expr 'all:fam.every(function(s){return s.hom_ref || s.het || s.hom_alt})'
--family-expr 'all:fam.every(function(s){return s.affected || ! s.affected})'
I only have the 7 affected patients selected, not the 4 unaffected ones in the VCF output.

when I use:
--family-expr 'all:fam.every(function(s){return ! s.affected})'
I have an empty VCF output.

Thanks for taking care of this message.

Best.

[Dyslexia.pedigree.txt](https://github.com/brentp/slivar/files/9634416/Dyslexia.pedigree.txt)

[vep.merged_first_10000.vcf.gz](https://github.com/brentp/slivar/files/9634429/vep.merged_first_10000.vcf.gz)

**Comment by brentp** [comment]
Hi Gael,
for family expressions, slivar reports the IDs of affected samples only, this works intuitively for most cases, but indeed, can be confusing at times. 
If you want to do something with unaffected samples, you can use --sample-expr.

**Comment by gael-millot** [comment]
If the field generated by --sample-expr can then be used in slivar tsv -s, then my problem is indeed solved. Thanks !

**Comment by gael-millot** [comment]
However: what kind of expression can be written with --sample-expr to be sure to take systematically all the samples ?

**Comment by brentp** [comment]
> However: what kind of expression can be written with --sample-expr to be sure to take systematically all the samples ?

You'll have to describe more what you're trying to do.

**Comment by gael-millot** [comment]
Sorry. Slivar is used in a pipeline with parameters defined in a config file. An option of this pipeline would be to get the .tsv file without any filtering made on the VCF (just benefit from the annotations). --pass-only can do it for slivar expr if I understood well but slivar tsv requires the mandatory -s option. Thus, the idea would be to fill the -s option but being certain that no filter is made.

**Comment by gael-millot** [comment]
--sample-expr 'all:sample.GQ >= 0' seems to do not take all the samples (probably when GQ is .).
--sample-expr 'all:sample.DP >= 0' seems to do the job, but I would need to be sure (i.e., what about empty info in DP ?)

Thanks.

**Comment by brentp** [comment]
I think you can you can use `--sample-expr 'all:true'`

**Comment by gael-millot** [comment]
Works ! Thanks a lot !
