### ISSUE TITLE
Quickstart should contain info on how to create a pedigree file and what tool is recommended for combining trio VCF into single file

### ISSUE THREAD

**Issue by nurmians** [brentp/slivar#156]
I wanted to give slivar a try with my trio variant calls, but there is no information on how to create a pedigree file and how to combine multiple VCFs. I know there are many tools for that, but to minimize risk of incompatibility you should mention a tool that is tested to be compatible. For example, can I use annovar annotated VCF files?

**Comment by brentp** [comment]
Hi, I pushed a fix for the documentation of pedigree format.
slivar does not support effects added by annovar. You'll have to use VEP, snpEff, or bcftools.
You'll also need a single, jointly-called VCF, not ones that have been called separately and then merged.
