### ISSUE TITLE
"Unknown Impacts": splice_donor_5th_base, splice_donor_region, splice_polypyrimidine_tract

### ISSUE THREAD

**Issue by wwgordon** [brentp/slivar#157]
Hi Brent,

The current default VEP annotation appears to include 3 Consequences not contained in default-order.txt: 

`splice_donor_5th_base` `splice_donor_region` `splice_polypyrimidine_tract`

They all have `IMPACT == LOW`: 

http://useast.ensembl.org/info/genome/variation/prediction/predicted_data.html#consequences

I am using VEP version 110:
```
Versions:
  ensembl              : 110.584a8f3
  ensembl-funcgen      : 110.24e6da6
  ensembl-io           : 110.b1a0d57
  ensembl-variation    : 110.d34d25e
  ensembl-vep          : 110.1
  ```

I've added them to my custom *order.txt but thought you'd like to know.

On a minor note, the warning states:
>warning: unknown impact "splice_polypyrimidine_tract" from csq  "TAAA|splice_polypyrimidine_tract_variant&intron_variant&non_coding_transcript_variant|LOW|..." please report the variant at https://github.com/brentp/slivar/issues

...however I believe this is actually an unknown Consequence; the IMPACT is known ("LOW"). 

Cheers,
William

**Comment by brentp** [comment]
thanks for reporting, I have added these to the repo. The message means it's unknown to slivar, which does not exactly rely on the impact given by the tool.

**Comment by wwgordon** [comment]
Hi again Brent,

We're a bit confused with how exactly the "impactful" functionality works, specifically, which CSQ fields (in a VEP-annotated VCF) are considered. I was under the impression that only terms in the "[Consequence](https://useast.ensembl.org/info/genome/variation/prediction/predicted_data.html)" field were considered, but I see that `5_prime_UTR_premature_start_codon_gain_variant` is included in the default order, which I believe is an annotation from the UTRAnnotator plugin. Does this mean that all CSQ fields are considered when testing for "impactful"-ness?

If this is the case and we want to consider UTRAnnotator output, I think there are 4 additional terms to consider:

```
5_prime_UTR_premature_start_codon_gain_variant
5_prime_UTR_premature_start_codon_loss_variant
5_prime_UTR_uORF_stop_codon_gain_variant
5_prime_UTR_uORF_stop_codon_loss_variant
5_prime_UTR_uORF_frameshift_variant
```

Note: these are the UTRAnnotator terms from recent (>108) versions of VEP. The older "standalone" UTRannotator plugin used different terms.

**Comment by brentp** [comment]
Hi, slivar only considers the consequence field. It could be that `5_prime_UTR_premature_start_codon_gain_variant` is annotated by snpEff or bcftools, the file tries to include annotations commonly seen from all 3 of the major effect predictors.

**Comment by wwgordon** [comment]
Thanks for the clarification!
