### ISSUE TITLE
limit to only autosomes

### ISSUE THREAD

**Issue by prasundutta87** [brentp/slivar#170]
Hi @brentp ,

I am trying to get some de novo SVs for some genes with biallelic mode of inheritance. I am using this command-

`slivar expr --vcf autosomal_recessive_SVs/"$family"_panel_genes_SVs.vcf --trio "biallelic_denovo:(variant.CHROM != \"chrX\"||variant.CHROM != \"chrY\") && (kid.het||kid.hom_alt) && mom.hom_ref && dad.hom_ref && kid.DP >= 5 && mom.DP >= 5 && dad.DP >= 5 && (mom.DV + dad.DV) == 0" --ped $PED_FILE_PATH/"$family".ped --pass-only -o biallelic_de_novo_SVs/"$family"_de_novo_SVs_in_biallelic_genes.vcf`

However, I am still getting X chrosome SV VCF records. What might be the issue here? Is there a better way to limit myself only to autosomes for this?

Regards,
Prasun

**Comment by brentp** [comment]
hi, is it "chrX" or just "X" ?

**Comment by brentp** [comment]
instead of:
```
(variant.CHROM != \"chrX\"||variant.CHROM != \"chrY\")
```

you likely want:
```
(variant.CHROM != \"chrX\" && variant.CHROM != \"chrY\")
```

and note that you can use single quotes to simplify:

```
(variant.CHROM != 'chrX' && variant.CHROM != 'chrY')
```

**Comment by prasundutta87** [comment]
Hi @brentp .. thanks a lot for this. It has worked now.
