### ISSUE TITLE
Inquiry for vcf file

### ISSUE THREAD

**Issue by dbswls0322** [brentp/slivar#172]
Dear slivar developer,
 
 I'm deeply grateful your effort to develop and maintain this tool,

 I got one error during running slivar expr with slivar v0.3.1

![image](https://github.com/user-attachments/assets/000fc21a-a83e-4d13-a408-de03ed1d90ce)

 And this is my code

![image](https://github.com/user-attachments/assets/b2b692da-9ab5-42ef-baa4-dfeba8c671e9)

 I wondered whether I can only upload 1 merged vcf file or a number of vcf files.
 If it's only acceptable to upload 1 vcf file, then should I merge it using GLnexus no matter phenotype of sample (ex. normal, tumor)?

 Best Regards.

**Comment by brentp** [comment]
you can only send a single VCF to slivar. the && is interpreted by the shell as a 2nd command.
