### ISSUE TITLE
Group expression: Combine all affecteds and unaffecteds for filtering

### ISSUE THREAD

**Issue by nroak** [brentp/slivar#20]
I was trying to figure out a way to check any variant common to affecteds and not present in unaffecteds for each family in a cohort. I was trying to manipulate the function here, 
https://github.com/brentp/slivar/wiki/groups-in-slivar#multi-generational-pedigree

```
function proportion_kids_with_alt(kids) {
    var n = 0
    for(i=0; i < kids.length; i++){
      if(kids[i].alts == 1 && kid.AB < 0.2 && kid.AB < 0.8){
          n += 1
      }
    }
    return n / kids.length
}
```
Currently I see a way to do that is by using _alias_ file header

> affected1 affected2 unaffected1 unaffected2...

 Followed by writing an expression like,
```
 --group-expr "shared_affected:unaffected1.alts == 0 && unaffected1.DP > 10 \
    && unaffected2.alts == 0 && unaffected2.DP > 10 \
    && affected1.alts == 1 && affected2.alts == 1"
```

However, if the number of affecteds and unaffecteds differs for each family in a cohort, the only way I can think of is by writing a family specific expression.
Can you please help with a solution where I can do something like this,
```
 --group-expr "shared_affected:unaffecteds.alts == 0 && unaffecteds.DP > 10 \
    && affecteds.alts == 1 "
```

**Comment by brentp** [comment]
there's a sort of undocumented feature of the group files; if you end the column header with `s` and use a comma-separated list, it will be available to you as a javascript array. e.g.:

```
#affecteds    unaffecteds
s1,s3,s5   s2,s4,s6
o1,o3,o10,o12    o2,o4,o8,o9,o7
```
then in your functions.js:

```
function finder(aff, unaff) {
    for(i=0;i<aff.length;i++){
        if(aff[i].alts != 1) { return false; }
    }
    for(i=0;i<unaff.length;i++){
        if(unaff[i].alts != 0) { return false; }
    }
    return true
}
```

then on the command-line:
```
   --group-expr "shared_affected:finder(affecteds, unaffecteds)"
```

**Comment by nroak** [comment]
This is very helpful to know. Thank you, Brett.
So if one of the families does not have any unaffecteds available for comparison, should the alias file have 2 headers but only sample ids for afffecteds or just one column with affecteds?

On a related note, how does it handle missing genotypes if one of the affecteds doesn't have an alts call?

**Comment by brentp** [comment]
just leave it empty if there are none, so, e.g.:

```
#affecteds    unaffecteds
s1,s3,s5              s2,s4,s6
o1,o3,o10,o12    o2,o4,o8,o9,o7
                            p1,p2,p3
```

a missing genotype is available as `$sample.alts == -1`

let me know any more questions. The groups stuff has been used less, so there might be some problems, but they should be easily fixed.

**Comment by nroak** [comment]
Thank you for the prompt responses. This is extremely helpful.
Groups expression has been very handy for incomplete pedigrees with variable sizes.

**Comment by nroak** [comment]
I closed too soon. Still trying to resolve this. I have a joint vcf for each family (not cohort). So the alias file I'm supplying is for per family (some families only have affecteds and not unaffecteds). Now I want to run the same javascript and slivar command on different alias files. 
However for alias files like this it throws an error.
`#affecteds    unaffecteds
   p1,p2,p3                         `

`slivarpkg/groups.nim(62) parse_group_line
Error: unhandled exception: unexpected number of samples for line:'pq,p2,p3' with header:'affecteds	unaffecteds' [ValueError]`

**Comment by brentp** [comment]
I can reproduce this and have a fix. Here's a binary if you want to give it a try:
[slivar.gz](https://github.com/brentp/slivar/files/3015458/slivar.gz)

**Comment by nroak** [comment]
This is working now. Thank you for the quick fix, Brent!

**Comment by brentp** [comment]
great! thanks for reporting and for following up. If you have a cool analysis, I'd love to add it as an example to the wiki (just the commands, doesn't require sharing data). No worries if not.

**Comment by nroak** [comment]
Pleasure! I will keep you posted if I design something cool.

**Comment by brentp** [comment]
this is out in the latest release: https://github.com/brentp/slivar/releases/tag/v0.0.8
