### ISSUE TITLE
duo-del finds inherited deletions too

### ISSUE THREAD

**Issue by brentp** [brentp/slivar#25]
should differentiate between inherited and *de novo*

**Comment by nroak** [comment]
For larger pedigrees, is there a way to find out which pairs are being analyzed? 
Eg. in a 3 generational pedigree, a parent can also be a child. I see one sample id in the output would be great if both samples ids are included.
Can you please provide some header information for columns?

**Comment by brentp** [comment]
there is a column that says, e.g. `NotDad` meaning that `slivar` found sites that were not transmitted from the dad. Currently, this could also mean that dad had a deletion that was transmitted to the son.
slivar finds and checks all child-parent pairs and reports only strong events.

**Comment by brentp** [comment]
I will add a header for next release.

**Comment by brentp** [comment]
and meanwhile, just to clarify, the sample-id in the output is the child id.

**Comment by brentp** [comment]
@nroak , this has been updated in master ready for next release. I have a few more things to look into.
If you want to test a binary ahead of time, I am attaching here. 
[slivar.gz](https://github.com/brentp/slivar/files/3105019/slivar.gz)

The output now has a header and the columns are explained here: https://github.com/brentp/slivar/wiki/finding-deletions-in-parent-child-duos
both de novo and inherited deletions are reported.

**Comment by nroak** [comment]
This is great! I will test it out tomorrow.

**Comment by nroak** [comment]
This works perfectly well. Thanks.
