### ISSUE TITLE
Compound het screening in samples without trio information

### ISSUE THREAD

**Issue by syouligan** [brentp/slivar#32]
Hi Brent
I have tried to identify potential compound hets in a single sample where no trio information is available and it would appear this is not possible. I appreciate this may be due to the fact the variants are phased-by-inheritance but it still may be useful to identify co-located variants in each gene. Do you happen to have a work around that I may be able to use?
Thanks for your help!

**Comment by brentp** [comment]
This isn't supported right now in slivar as it would give way too many candidates. You could follow the documentation for the slivar compound-hets as it is (with `lenient_ar` and `lenient_denovo`) and then just grouping by gene. If you do that and show that there are few enough candidates, I might consider a tool to add this.

**Comment by syouligan** [comment]
Excellent, Ill look into it. Perhaps related to the CSQ parsing issue you posted, a filtering option that may be useful to reduce candidates would be the IMPACT field in the CSQ output as this can help limit to essentially just protein altering variants (IMPACT == HIGH || IMPACT == MODERATE). Cheers

**Comment by brentp** [comment]
yes, it would be nice to facilitate CSQ filtering but that can add some complexity. Meanwhile, you could write a javascript function to filter on your desired impacts and then use that as a slivar filter.

**Comment by brentp** [comment]
I am adding to compound-het  for next release such that it will allow a singleton sample or a sample with only 1 parent represented. Should be ready next week.

**Comment by brentp** [comment]
this is out in latest release. thanks for suggesting.

**Comment by syouligan** [comment]
Awesome, I'll go it a go. Thanks a lot!
