### ISSUE TITLE
use RankSum's for filtering

### ISSUE THREAD

**Issue by brentp** [brentp/slivar#36]
via @adw222 
many variants that pass other filters often have high MQRankSum scores, this could be a filter or added to default list of tsv exports.

**Comment by genomics-geek** [comment]
I noticed these fields are not accessible in INFO.  I assumed all fields in INFO would be.

**Comment by brentp** [comment]
they are available, I am using them in some cases. can you expand on what you're seeing?

**Comment by genomics-geek** [comment]
I take that back, yes it is working.  For some reason before I was getting `unknown attribute` but could be related to what I was working on with this https://github.com/brentp/slivar/issues/27#issuecomment-534774933.

**Comment by brentp** [comment]
i also have a pending change in dev that prevents it from stopping (just issues a warning) if, for example if you ask for `BaseQRankSum` but it happens to be missing from a few variants. I'll get the release out this week or next.

**Comment by genomics-geek** [comment]
It was probably related to that.

**Comment by brentp** [comment]
closing for now. Please re-open with more info if problem persists.
