### ISSUE TITLE
Comparing genotypes

### ISSUE THREAD

**Issue by JakeHagen** [brentp/slivar#37]
Hello Brent

I am trying to use slivar to compare genotypes between two different variant callers (using one variant caller as a quick validation). My current workflow is to put the GQ, AD, and GT from the second caller into the FMT field of the first vcf. I would then like to use slivars expressions to compare, but it seems this I am not able to do this. ie if GQ > 30 and GT[0] == otherGT[0] 

I briefly read the code and it seems GT is only parsed into an alts number and is not available as a string, is this correct? To get around this I have tried something like "(parseInt(otherGT[0]) + parseInt(otherGT[2])) == alts" but I cant seem to get that to work either.

Do you have any suggestions on how to do this in slivar?

Thanks
Jake

**Comment by brentp** [comment]
can you share the header and 1 line of the VCF so I can understand better what you mean?

**Comment by brentp** [comment]
also, currently, slivar skips string fields in samples, but I could make it add those to each sample if there is a need.

**Comment by JakeHagen** [comment]
```
##FORMAT=<ID=DVGQ,Number=1,Type=Integer,Description="GQ from deepvariant">
##FORMAT=<ID=DVGT,Number=1,Type=String,Description="GT from deepvariant">
##FORMAT=<ID=DVAD,Number=R,Type=Integer,Description="Read depth for each allele">
```

```
1       1938830 rs71630949      C       T       1827.2  .       AC=1;AF=0.1;AN=10;AS_BaseQRankSum=-1;AS_FS=0;AS_MQ=60;AS_MQRankSum=0;AS_QD=13.44;AS_ReadPosRankSum=0.9;AS_SOR=0.686;BaseQRankSum=-0.98;DB;DP=435;ExcessHet=3.0103;FS=0;MLEAC=1;MLEAF=0.1;MQ=60;MQRankSum=0;QD=13.44;ReadPosRankSum=0.928;SOR=0.686      GT:AD:DP:DVAD:DVGQ:DVGT:GQ:PL   0/0:61,0:61:.,.:.:.:99:0,120,1800       0/1:65,71:136:65,72:69:0/1:99:1837,0,1748       0/0:56,0:56:.,.:.:.:99:0,120,1800       0/0:80,0:80:.,.:.:.:99:0,120,1800       0/0:102,0:102:.,.:.:.:99:0,120,1800
```

I have attach the relevant lines of the header and one line of the VCF. Let me know if you need anymore.

I must have missed the bit about skipping string fields in the code, I think that makes comparing genotypes fields in this manner impossible.

Either way thank you very much for your help.

**Comment by JakeHagen** [comment]
After considering this some more, I think I will try to handle this differently. Since I like to decompose the VCF, the "DVGT" wouldnt be handled correctly anyway. Sorry to bother you with this, and thank you for your time.

**Comment by brentp** [comment]
if you have Number=R, then it would decompose correctly. 
As I mentioned, slivar currently ignores sample fields that are strings, but I can support this if there is a need.

**Comment by JakeHagen** [comment]
If it isn't too much trouble, I would would certainly make use of strings in the sample fields.

**Comment by seboyden** [comment]
@brentp Manta generates the FT tag in the Sample field that is a string.  I would like to be able to filter Manta output for e.g. kid.FT == 'PASS'

**Comment by brentp** [comment]
Hi, I have just pushed a change that allows users to opt-in to this by setting an environment variable, e.g. 
```
SLIVAR_FORMAT_STRINGS=1 slivar expr ... --trio "ft:'FT' in kid and kid.FT == 'PASS'" ..
```
and then `unset SLIVAR_FORMAT_STRINGS` 

I'd appreciate it if you give it a try and verify it's working for your needs.

[slivar.gz](https://github.com/brentp/slivar/files/4781653/slivar.gz)
