### ISSUE TITLE
support for family expressions

### ISSUE THREAD

**Issue by brentp** [brentp/slivar#39]
using trios is convenient, but not complete. given a singleton, a duo, a trio, and a quad, we have to write 4 expressions and abuse --sample-expr to do so. 
We can follow [gemini](https://github.com/arq5x/gemini) and get around this by doing family-based expressions. For example a *de novo* on a quad (with sib affected or not), trio, duo, singleton, and e.g. a proband and an affected aunt would all use:
```Javascript
fam.every(function(s) {return s.het == s.affected && s.hom_ref == !s.affected})
```
to require that all affected samples are het and unaffected samples are all homozygous reference. Once [quickjs](https://bellard.org/quickjs/) has matured, and I update slivar to use that instead of [duktape](https://duktape.org), that expression will be:

```Javascript
fam.every(s => s.het == s.affected && s.hom_ref == !s.affected)
```
this can simply be a function in which case, it would appear as:
```Javascript
fam.every(affected_only)
```
with the function defined elsewhere as:
```Javascript
function affected_only(sample) {
    return sample.GQ > 10 && sample.het == sample.affected && sample.hom_ref == !sample.affected
}
```

This will require adding a `--family-expr` argument (in addition to `--trio`, `--group-expr`, `--sample-expr`), but this can use the group machinery internally and it will likely replace many uses of `--group-expr` which is more complex since it requires the alias file.

The expression will have access to:
+ fam.n_affected [int]
+ fam.n_unaffected [int]
+ fam.n_male [int]
+ fam.n_female [int]
+ fam.trio [bool] ( see below)
+ fam [Array of Samples]

Note that fam is the array of samples with additional attributes.

For `family-expr`, the sample id of each affected sample will be added to the INFO field. If no affected sample is found, then the family is added to the INFO. 

Note that given 2 affected kids, this machinery could be used to find shared *de novos* easily--and that is likely what would be desired.It would require different logic for a de novo in either affected. Since that case is handled by --trio, this is not a problem.

## fam.trio

The remaining issue is how this works when specified in conjunction with --trio. E.g.:
```
  --trio "denovo:denovo(mom, dad, kid)" \
  --family-expr "denovo:denovo_fam(fam)" \
```
would mean that trios would be evaluated and reported twice. 
in many cases, we want the convenience of trio for a true trio and the family for families with something other than `mom`, `dad`, `kid`. For this we can have e.g.

```
  --trio "denovo:denovo(mom, dad, kid)" \
  --family-expr "denovo:!fam.trio && denovo_fam(fam)" \
```
where fam.trio is true **iff** `mom`, `dad`, `kid` are all of the samples within the family.

## javascript

Here is the start of the javascript to support family-based evaluations generally. I think having
+ `segregating_dominant`
+ `segregating_de_novo`
+ `segregating_recessive`

will be sufficient. These all include custom code for chrX, but only those 3 functions will be called by the user.

```Javascript
function segregating_dominant_x(s) {
  // this is an internal function only called after checking sample quality and on X
  if(!s.affected) { return s.hom_ref }
  if(s.sex == "male") {
    for(var i=0; i < s.kids.length; s++) {
      var kid = s.kids[i];
      // kids of affected dad must be affected.
      if(!kid.affected) { return false; }
    }
    // mom of affected male must be affected.
    if(s.mom && !(s.mom.affected && s.mom.het)){ return false; }

    return s.hom_alt || (s.het && s.AB < 0.2 && s.AB > 0.8)
  }
  if(s.sex != "female"){return false; }
  // this block enforces inherited dominant, but not find de novos
  if(s.mom || s.dad) {
    if(!((s.mom && s.mom.affected && s.mom.het) || (s.dad && s.dad.affected))) { return false;}
  }
  return s.het && s.AB > 0.2 && s.AB < 0.8;
}


function segregating_dominant(s) {
  if(s.GQ < 10 || s.unknown) { return false; }
  if(variant.CHROM == "chrX" || variant.CHROM == "X") { return segregating_dominant_x(s); }
  if (s.affected) {
     return s.het && s.AB > 0.2 && s.AB < 0.8
  }
  return s.hom_ref && s.AB < 0.01
}


function segregating_recessive_x(s) {
  // this is an internal function only called after checking sample quality and on X
  if(s.sex == "female") {
    return s.affected == s.hom_alt;
  } else if (s.sex == "male") {
    return s.affected == (s.het || s.hom_alt);
  } else {
    return false;
  }

}

function segregating_recessive(s) {
  if(s.GQ < 10 || s.unknown) { return false; }
  if(variant.CHROM == "chrX" || variant.CHROM == "X") { return segregating_recessive_x(s); }
  if(s.affected){
    return s.hom_alt
  }
  return s.het || s.hom_ref
}
```

**Comment by asapb** [comment]
Hi Brent, 

This is probably what I'm after because I'm dealing with incomplete family data with carrier with a healthy sibling, but an affected cousin, and affected second cousin etc, but no complete trios.

Thank you.

**Comment by brentp** [comment]
good to hear, this is implemented. it will be out in next release once I document better.
meanwhile you can try the attached binary (further updated from your other issue). and use like:
```
 --family-expr "segregating:fam.every(function(s) {return s.het == s.affected && s.hom_ref == !s.affected && s.GQ > 10})"
```
this just requires that all of the samples in the extended family have the same family id in the pedigree file that you send to slivar.

[slivar.gz](https://github.com/brentp/slivar/files/3424598/slivar.gz)

**Comment by asapb** [comment]
Fantastic, thank you very much!
(Downloaded _this_ new binary and will run it now.)

**Comment by brentp** [comment]
I originally uploaded the wrong binary, so if you got it more than a minute ago, then you might try again. you'll know by seeing if `slivar expr` without any arguments shows the new `--family-expr` option. I'm happy to hear any feedback.

**Comment by asapb** [comment]
Downloaded the binary again. Same MD5 checksums as the one I downloaded earlier today:
fe0b80abb1e9d65b3745bbe26806bbbf

(Has the `--family-expr` option when running `slivar expr`.) 

Thank you!

**Comment by asapb** [comment]
Hi Brent,

It works! Brilliant and so very useful to have `--family-expr`.

Thank you very much.

**Comment by brentp** [comment]
excellent. thanks for following up.

**Comment by asapb** [comment]
Is the `affected_only` function really supposed to say that the samples that are homozygous reference are not unaffected?

`sample.hom_ref == !sample.unaffected` or is it a typo and it should it say they are not affected

`sample.hom_ref == !sample.affected`

```
function affected_only(sample) {
    return sample.GQ > 10 && sample.het == sample.affected && sample.hom_ref == !sample.unaffected
}
```

**Comment by brentp** [comment]
you are correct. should be `sample.hom_ref == !sample.affected`. I have updated the text above. thanks for noting.

**Comment by asapb** [comment]
This special edition binary of slivar (made for issue#39 version 0.1.6) works for me... until I try using the `--info` option. (An option I have successfully used with the official release of slivar v. 0.1.5 and trios (kid, mom, dad) data.)

slivar (v. 0.1.6) using `--info` with `--family-expr` doesn't work for me. Maybe I'm missing something and writing my query wrong?


This works:
```
# Command to run slivar
$SRC/bin/slivar expr \
	--pass-only \
	--vcf $vcf \
	--ped $ped \
	--out-vcf $out \
	--alias $alias \
	--js $js \
	--family-expr "segregating:fam.every(function(s) {return s.het == s.affected && s.hom_ref == !s.affected && s.GQ > 10})" 
```

but this doesn't work:
```
# Filters
info="variant.call_rate > 0.9"

# Command to run slivar
$SRC/bin/slivar expr \
	--pass-only \
	--vcf $vcf \
	--ped $ped \
	--out-vcf $out \
	--alias $alias \
	--js $js \
	--gnotate $gnotation \
	--info "$info" \	
	--family-expr "segregating:fam.every(function(s) {return s.het == s.affected && s.hom_ref == !s.affected && s.GQ > 10})" 
```

Neither does exchanging `--info "$info \` for hard coding it into the slivar run command as 

```--info "variant.call_rate > 0.9" \```

Error message:
```
/path/to/slivar/0.1.6/bin/slivar expr --pass-only --vcf /path/to/my.vcf --ped /path/to/my.ped --out-vcf /path/to/my.flt.vcf --alias /path/to/my.group --js /path/to/slivar_functions.issue39.js --gnotate /path/to/gnotations/gnomad.hg38.v2.zip --info 'variant.call_rate > 0.9' '	'
slivar version: 0.1.6
argparse.nim(576)        parse
Error: unhandled exception: Unknown arguments: @["\t"] [UsageError]
```
As you can see from the STDERR log excerpt `--family-expr` is empty just displayed as `'	'`.

What am I missing?
 
Thank you

**Comment by brentp** [comment]
I have a few more bugs to work out, but this doesn't seem like one of them. make sure there are not tabs in your command. e.g. it's not `variant.call_rate\t>0.9` or something.

**Comment by brentp** [comment]
oh. I see the problem. You have to use single-quotes for the --family-expr, because it contains `!`.

**Comment by nroak** [comment]
Thanks for adding this brent! I haven't used it yet but I'm very interested in this function. I will test it out once it's out in next release.

**Comment by asapb** [comment]
Hi Brent,

Double quotes work just fine with `--family-expr` containing a `!`. 
(Used it in my original run -- please see above) without any problems.

The issue was that I had accidentally hit the tab '\t' key not inside the `info` variable, but on the row in my `slivar expr` with the `--info` line like this:

`--info "$info" \`[TAB]

Remove the tab and now slivar version 0.1.6 runs again.

Thank you very much!

**Comment by brentp** [comment]
ok. you do have to be careful with ! because in some context bash will try to interpret it.

**Comment by asapb** [comment]
Got it. Thank you!

**Comment by asapb** [comment]
Hi again, what do you mean by `--family-expr` doesn't require a group to be defined and specified through the `--alias` option?

When I was running slivar with the `--group-expr` I would provide a path to the group aliases through `--alias`.

I have been doing the same when using `--family-expr`. When I don't provide the `--alias` option I don't get anything but header lines in the VCF file.

How can I provide the family list `fam`?
Is it also through the `--alias` option, but where my family is just a list like this?

```
#fam
family_id_1
family_id_2
family_id_3
```

Thank you

**Comment by brentp** [comment]
I wondered how this was working for you. I fixed that bug shortly after uploading that binary. Here is the latest.
With this you just specify a `--ped` where all members of the same family have the same family_id.


[slivar.gz](https://github.com/brentp/slivar/files/3444828/slivar.gz)

**Comment by brentp** [comment]
Also, thanks for your persistence, you're trying out a bleeding-edge feature here which will have some problems.

**Comment by asapb** [comment]
Well, when I use `--family-expr` and I provide a group file, specified through `--alias` I got numbers out... but they didn't necessarily make sense.

Thank you for your patience with my questions and thank you very much for the new binary!
Will test it immediately.

**Comment by asapb** [comment]
Have another question.

Why did you define a function

```
function affected_only(sample) {
    return sample.GQ > 10 && sample.het == sample.affected && sample.hom_ref == !sample.affected
}
```

and call it `affected_only` if it doesn't also include `sample.hom_alt == sample.affected`?

Shouldn't it be something like

```
function affected_only(sample) {
    return sample.GQ > 10 && (sample.het == sample.affected || sample.hom_alt == sample.affected) && sample.hom_ref == !sample.affected
}
```

for the function to capture all possibilities of `affected_only` or am I missing something?

**Comment by brentp** [comment]
that's a fair point. I think your incantation would be better. I am collecting these more permanently in [js/my.js](https://github.com/brentp/slivar/blob/master/js/my.js) where I have `segregating_*` functions, including `segregating_recessive` and `segregating_dominant` which capture hom_alt and het. happy to hear more feedback on those.

**Comment by asapb** [comment]
Re: The javascript file in js/my.js: 
Cool, I want to try running it with `segregating_denovo`, so will run again. 
Thanks for making the file! Very handy!

Re: Newest binary (slivar v. 0.1.6 MD5 checksum a76b4ea60e67f73f78bc23a70621998d):
If I run the newest binary _without_ specifying a group with the `--alias` option I get the same result as when I ran the previous binary (slivar v. 0.1.6 MD5 checksum fe0b80abb1e9d65b3745bbe26806bbbf) specifying the group with `--alias`.

The family I'm studying is unusual in the sense that I don't have any trios. I have a carrier and healthy sibling, affected cousin, affected second cousin etc.

So the way I made my group was in the style of your groups when you worked with multi-generational pedigrees:

```
#healthy   carrier   affected
s1   s2,s3,s4   s5,s6,s7
```

where `s1` is the healthy individual, `s2`, `s2` and `s3` are carriers and `s5`, `s6` and `s7` are affected by the disease. Each column is separated by a tab.

However, not having to specify the group makes things much easier... especially since there might be more than one proband (in this case `healthy`) in the future.

**Comment by brentp** [comment]
can you share the full command you are using? `--family-expr` expects only a `--ped` file (to indicate the families and affections), not `--alias` or `--group-expr`.

**Comment by asapb** [comment]
What I meant was that the `SLIVAR_SUMMARY_FILE` from both runs show the same counts.
Below is what I ran for each binary of slivar.

**Run using second last version of slivar version 0.1.6 
(MD5 checksum fe0b80abb1e9d65b3745bbe26806bbbf)**

```
slivar expr \
        --pass-only \
        --vcf $vcf \
        --ped $ped \
        --out-vcf $out \
        --alias $alias \
        --gnotate $gnotation \
        --js $js \
        --info "$info" \
        --family-expr "het:fam.every(function(s) {return s.het == s.affected && s.hom_ref == !s.affected && s.GQ > 10})" \
        --family-expr "hom_alt:fam.every(function(s) {return s.hom_alt == s.affected && s.hom_ref == !s.affected && s.GQ > 10})" \
        --family-expr "any_affected:fam.every(function(s) {return (s.het == s.affected || s.hom_alt == s.affected) && s.hom_ref == !s.affected && s.GQ > 10})" \
        --family-expr "seg_dom:fam.every(segregating_dominant)" \
        --family-expr "seg_rec:fam.every(segregating_recessive)"
```

with a group file (called with `--alias`)

**`family.group`**

```
#healthy	carriers	affecteds
s1	s2,s3,s4	s5,s6,s7,s8,s9
```

**Run using the latest binary of slivar version 0.1.6 
(MD5 checksum a76b4ea60e67f73f78bc23a70621998d)**

This was run without specifying a group (i.e., without the `--alias` option)

```
slivar expr \
        --pass-only \
        --vcf $vcf \
        --ped $ped \
        --out-vcf $out \
        --gnotate $gnotation \
        --js $js \
        --info "$info" \
        --family-expr "het:fam.every(function(s) {return s.het == s.affected && s.hom_ref == !s.affected && s.GQ > 10})" \
        --family-expr "hom_alt:fam.every(function(s) {return s.hom_alt == s.affected && s.hom_ref == !s.affected && s.GQ > 10})" \
        --family-expr "any_affected:fam.every(function(s) {return (s.het == s.affected || s.hom_alt == s.affected) && s.hom_ref == !s.affected && s.GQ > 10})" \
        --family-expr "seg_dom:fam.every(segregating_dominant)" \
        --family-expr "seg_rec:fam.every(segregating_recessive)"
```


I like the new version of slivar more though because there will be times when I will have more than one healthy individual (proband), and I don't think that your multi-generational pedigree group would work with more than one proband per run.

**Comment by brentp** [comment]
this is out here: https://github.com/brentp/slivar/releases/tag/v0.1.6

thanks for the feedback and let me know any other issues.

**Comment by genomics-geek** [comment]
This is a great feature! We also deal with incomplete families.

**Comment by asapb** [comment]
Thank you very much Brent. Will transfer from the beta releases of v0.1.6 to your official release.

**Comment by nroak** [comment]
Brent, I wanted to confirm that in the expression above, **s.affected** is picked from the PED file's phenotype field, correct?

**Comment by brentp** [comment]
that is correct. however, in slivar, it's current true for affected and false for everything else.

**Comment by jxchong** [comment]
@brentp I think we want to be able to distinguish unaffected from missing/unknown (i.e. we would not want to restrict upon the genotype of the unknown/missing individual).

**Comment by nroak** [comment]
> that is correct. however, in slivar, it's current true for affected and false for everything else.

Got it, does it mean it's more like this?
 -9 missing
      0 unaffected
      1 affected

I'm curious because I have coded it as 1=unaffected, 2=affected, but that might lead both being read as TRUE=affected. I'm missing a few test variants from my query, that might be the reason.

**Comment by brentp** [comment]
now, `affected` is coded as:
```
s.affected = toks[5].toLowerAscii in  ["2", "affected", "yes"]
```
so anything other than the 3 things in [] is false.

I am adding a sample.phenotype attribute which allows determining which samples are unknown. it uses this logic:
```Nim
    if toks[5].toLowerAscii in ["2", "affected", "yes"]:
      s.phenotype = 2
    elif toks[5].toLowerAscii in ["1", "unaffected", "no"]:
      s.phenotype = 1
    else:
      try:
        s.phenotype = parseInt(toks[5])
      except:
        s.phenotype = -9
```    

the alternative is to have `phenotype` be a string and then whatever was in the ped file will be transferred to that attribute unchanged. thoughts?

**Comment by nroak** [comment]
I like your current logic since it's in line with the standard PLINK format. It's very helpful to have consistent notations across different tools. Maybe just having it spelled out would help or a sample PED file to clarify?

**Comment by brentp** [comment]
well, current one ignores an unknown and just sets it to a binary affected or not.

**Comment by brentp** [comment]
i just pushed a change to a dev branch that exposes `sample.phenotype` as a string that matches whatever was in the pedigree file. this will be out next month.

**Comment by nroak** [comment]
Brent, I'm trying out the `--family-expr` function per the code below which takes in the 3 inheritance functions from your [my.js](https://github.com/brentp/slivar/blob/master/js/my.js) and affected_only function as described above:
```
~/resources/slivar/slivar expr \
--vcf test.vcf.gz \
--pass-only \
--region chr4:56907900-56935847 \
--out-vcf test.segregating.vcf \
--js my.js \
--ped test.ped \
--family-expr "segregating:fam.every(affected_only)" \
--family-expr "seg_dom:fam.every(segregating_dominant)" \
--family-expr "seg_rec:fam.every(segregating_recessive)" \
--family-expr "seg_denovo:fam.every(segregating_denovo)"

function affected_only(sample) {
    return sample.GQ > 10 && (sample.het == sample.affected || sample.hom_alt == sample.affected) && sample.hom_ref == !sample.affected
}
```

I'm noticing that this expression is not able to capture all segregating variants in some families in this region. I can share test ped and vcf files for this code securely.

**Comment by brentp** [comment]
sure. for the VCF, can you narrow it down to just a single variant that does not pass?

**Comment by nroak** [comment]
Sure, I have just sent the files to your gmail, after restricting the variants to a small region.

**Comment by nroak** [comment]
Brent, can you please document the family expression in Wiki when you get a chance?
