### ISSUE TITLE
SV filtering

### ISSUE THREAD

**Issue by erampersaud** [brentp/slivar#43]
Hi Brent,

I'm wondering if slivar can be used to filter VCF's generated using SVTYPER with snpEff annotations? I'm interested in identifying potentially inherited CNV/SVs.

 I've found your SNV/indel pipeline very useful as Ninad Oak in our group has already implemented it and we are gaining a lot of useful information. If this can be extended to CNV/SVs that would be really great.

Thank you,
Evadnie Rampersaud

**Comment by brentp** [comment]
hi, pretty much anything in the INFO and any non-string in the sample field is available via slivar. So, yes it works with SVs/CNVs, for example, we filter for denovo deletions like this:

```
INFO.SVTYPE == "DEL" && kid.het && mom.hom_ref && dad.hom_ref && kid.DHFFC < 0.7 && mom.DHFFC > 0.8 && dad.DHFFC > 0.8
```
where DHFFC is a sample annotation added by [duphold](https://github.com/brentp/duphold)

I'm happy to help further if you have an example of the type of filtering that you are attempting.

**Comment by erampersaud** [comment]
Thanks Brent. I was trying to use the affected/unaffected filtering with an alias file. I kept the filters limited as a first run to check that it worked. 

This is what the parameter file looks like:
/rgs01/project_space/PCGP/Control/common/reference/slivar/slivar expr \
--pass-only \
--vcf $i.clean.sorted.vcf.gz \
--out-vcf $i.clean.sorted.slivar.vcf \
--js functions.js \
--alias HL3056.alias \
--group-expr "shared_affected:finder(affecteds, unaffecteds)"
done;

Here is a snapshot of the input file (hope this shows up!)
![Capture](https://user-images.githubusercontent.com/51176056/66496913-48870600-ea81-11e9-8107-08d7cf169333.JPG)

The alias file looks like this:
#affecteds      unaffecteds
SJHL057771_G1-SB708031,SJHL057772_G1-SB708032,SJHL057779_G1-SB708066    SJNORM057636_G1-SC314930,SJNORM057673_G1-SC314970,SJNORM057695_G1-SC314992,SJNORM057728_G1-SC315025

I can attach a mini sliced VCF file if you prefer.

**Comment by erampersaud** [comment]
The original file had NAN, NA, etc and looked like this. I converted to "." for the NAN's.
![Capture](https://user-images.githubusercontent.com/51176056/66497162-afa4ba80-ea81-11e9-9100-f9c1f4343915.JPG)

**Comment by brentp** [comment]
can you clarify what is *not* working?

**Comment by erampersaud** [comment]
Yes that may help :-)
I found it odd that across multiple chromosomes, not one variant was even falsely identified as being shared. This may very well be the case because I would expect that inherited SVs would be rare but i wanted to be sure it wasn't some issue with the filtering of this form of VCF in particular.
![Capture](https://user-images.githubusercontent.com/51176056/66498676-0e6b3380-ea84-11e9-8b65-7987d8578762.JPG)

I will share the log in a second.
BTW, this is just one family that I am running so again perhaps this isn't unexpected. What has been your experience with this?

**Comment by erampersaud** [comment]
The log I just uploaded shows that many chromsome-specific slivar output files (eg. chr3,snpeff.ann.vcf.clean.sorted.slivar.vcf" have the same size and that size represents just the sample ids (sample ids include more than just the samples in this particular pedigree).

**Comment by erampersaud** [comment]
Apologies for the multiple and long posts. I am pasting in the log from slivar which seems to indicate that it ran ok but just didn't find any shared variants. So the question is whether this is to be expected.

slivar version: 0.1.2

378 samples matched in VCF and PED to be evaluated
[slivar] 10000 chr1:5575566 evaluated 10000 variants in 6.4 seconds (1566.9/second)
[slivar] 20000 chr1:10273858 evaluated 10000 variants in 6.5 seconds (1531.2/second)
[slivar] 100000 chr1:48777043 evaluated 100000 variants in 52.0 seconds (1924.2/second)
[slivar] 200000 chr1:94489201 evaluated 100000 variants in 64.1 seconds (1559.3/second)
[slivar] 300000 chr1:143201682 evaluated 100000 variants in 57.5 seconds (1740.3/second)
[slivar] 400000 chr1:183956896 evaluated 100000 variants in 62.4 seconds (1602.5/second)
[slivar] 500000 chr1:229788368 evaluated 100000 variants in 63.6 seconds (1571.5/second)
[slivar] Finished. evaluated 542186 total variants and wrote 0 passing variants.
sample  shared_affected
SJALL045793_G1-DAAR_A5783       0
SJALL045794_G1-BRAR_A5784       0
SJALL045797_G1-ANMC_A5787       0
SJALL045799_D1-A5128    0
SJALL045799_G1-A5128    0
SJALL045800_D1-BRMC_A5785_NODE  0
SJALL045800_G1-BRMC_A5785_NODE  0
SJALL057849_G1-FHS_571  0
SJALL057851_G1-FHS_123  0
SJALL057859_G1-FHS_296  0
SJALL057872_D1-1974     0
SJALL057872_G1-1351     0
SJALL057875_G1-1288     0
SJALL057876_G1-FHS_493  0
SJALL057880_D1-1551     0
SJALL057881_G1-1525     0
SJALL057882_G1-FHS_126  0
SJALL057887_G1-FHS_131  0
SJALL057890_D1-1645     0
SJALL057890_G1-FHS_608  0
SJALL057891_D1-1684     0
SJALL057891_G1-1695     0
SJBALL004230_D2-TB-09-0494      0
SJBALL004230_G3-TB-17-10714     0
SJBALL019091_D1-TB-96-0940      0
SJBALL048454_G2-TB-17-07293     0
SJBALL048470_G1-TB-17-06275     0
SJBALL055338_G1-TB-17-10876     0
SJBALL055347_G1-TB-17-11894     0
SJBALL056715_G1-TB-18-01200     0
SJBALL056720_G1-TB-18-01203     0
SJBALL056721_G1-TB-16-05132     0
SJBALL056722_G1-TB-16-05130     0
SJBALL056727_G1-TB-18-01760     0
SJBALL056728_G1-TB-18-01761     0
SJBALL057897_D1-TB-18-03239     0
SJBALL057898_D1-TB-18-03240     0
SJBLACA057889_G1-FHS_138        0
SJBRCA057627_G1-SC314916        0
SJBRCA057655_G1-SC314949        0
SJBRCA057842_G1-1736    0
SJCLL057860_G1-FHS_258  0
SJCML057800_G1-FHS_314  0
SJHL018667_G2-TB-16-08275       0
SJHL019287_G2-TB-16-08650       0
SJHL019344_G2-TB-17-03044       0
SJHL049036_G1-TB-16-07072       0
SJHL049037_G1-TB-16-08271       0
SJHL049038_G1-TB-16-09682       0
SJHL049039_G1-TB-16-09681       0
SJHL049040_G1-TB-17-00166       0
SJHL049041_G1-TB-17-00988       0
SJHL049042_G1-TB-17-00989       0
SJHL049043_G1-TB-17-01579       0
SJHL049044_G1-TB-17-01580       0
SJHL049045_G1-TB-17-01581       0
SJHL049046_G1-TB-17-01582       0
SJHL049047_G1-TB-17-01739       0
SJHL049048_G1-TB-17-01772       0
SJHL049049_G1-TB-17-02171       0
SJHL049050_G1-TB-17-02172       0
SJHL049051_G1-TB-17-02174       0
SJHL049052_G1-TB-17-02161       0
SJHL050592_G1-TB-17-02754       0
SJHL050593_G1-TB-17-02755       0
SJHL050596_G1-TB-17-07848       0
SJHL050597_G1-TB-17-08416       0
SJHL050600_G1-TB-17-08473       0
SJHL050601_G1-TB-17-04084       0
SJHL050602_G1-TB-17-04541       0
SJHL050952_G1-TB-17-09468       0
SJHL056702_G1-TB-17-08586       0
SJHL056707_G1-TB-17-12575       0
SJHL056711_G1-TB-18-00526       0
SJHL056712_G1-TB-18-01215       0
SJHL056714_G1-TB-17-08491       0
SJHL057634_G1-SC314928  0
SJHL057637_G1-SC314931  0
SJHL057658_G1-SC314953  0
SJHL057661_G1-SC314956  0
SJHL057664_G1-SC314960  0
SJHL057685_G1-SC314982  0
SJHL057729_G1-SC315026  0
SJHL057730_G1-SC315027  0
SJHL057737_G1-SC315034  0
SJHL057740_G1-SC315037  0
SJHL057743_G1-SC315040  0
SJHL057744_G1-SC315041  0
SJHL057745_G1-SB165996  0
SJHL057746_G1-SB166005  0
SJHL057747_G1-SB166021  0
SJHL057748_G1-SB166029  0
SJHL057749_G1-SB166030  0
SJHL057751_G1-SB166079  0
SJHL057752_G1-SB166090  0
SJHL057753_G1-SB166110  0
SJHL057754_G1-SB166174  0
SJHL057755_G1-SB166225  0
SJHL057756_G1-SB888542  0
SJHL057757_G1-SB888543  0
SJHL057758_G1-SB490445  0
SJHL057759_G1-SB490509  0
SJHL057760_G1-SB490527  0
SJHL057761_G1-SB490547  0
SJHL057762_G1-SB659884  0
SJHL057763_G1-SB659899  0
SJHL057764_G1-SB659900  0
SJHL057766_G1-SB708005  0
SJHL057767_G1-SB708007  0
SJHL057768_G1-SB708010  0
SJHL057769_G1-SB708011  0
SJHL057770_G1-SB708012  0
SJHL057771_G1-SB708031  0
SJHL057772_G1-SB708032  0
SJHL057773_G1-SB708040  0
SJHL057774_G1-SB708041  0
SJHL057775_G1-SB708043  0
SJHL057776_G1-SB708044  0
SJHL057777_G1-SB708063  0
SJHL057778_G1-SB708065  0
SJHL057779_G1-SB708066  0
SJHL057780_G1-SB800410  0
SJHL057781_G1-SB861312  0
SJHL057782_G1-SB861319  0
SJHL057783_G1-SB931102  0
SJHL057784_G1-SC091578  0
SJHL057785_G1-SC091580  0
SJHL057786_G1-SC091581  0
SJHL057799_G1-AE10092_0803      0
SJHL057802_G1-FHS_007   0
SJHL057805_G1-FHS_022   0
SJHL057816_G1-FHS_039   0
SJHL057895_G1-TB-18-03160       0
SJLYM057867_G1-FHS_375  0
SJMEL057653_G1-SC314947 0
SJMEL057717_G1-SC315014 0
SJMEL057718_G1-SC315015 0
SJMEL057721_G1-SC315018 0
SJMM057865_G1-FHS_385   0
SJMYF057850_D1-FHS_122  0
SJMYF057854_D1-FHS_125  0
SJNEUTP057862_G1-FHS_279        0
SJNHL050948_G1-TB-17-06848      0
SJNHL056444_G2-TB-18-03158      0
SJNHL057677_G1-SC314974 0
SJNHL057801_G1-FHS_335  0
SJNHL057808_G1-FHS_006  0
SJNHL057826_G1-FHS_018  0
SJNHL057831_G1-FHS_051  0
SJNHL057837_G1-FHS_053  0
SJNHL057863_G1-FHS_374  0
SJNORM050591_G1-TB-17-02753     0
SJNORM050594_G1-TB-17-06596     0
SJNORM050595_G1-TB-17-06597     0
SJNORM050598_G1-TB-17-08417     0
SJNORM050599_G1-TB-17-08418     0
SJNORM050947_G1-TB-17-06846     0
SJNORM050949_G1-TB-17-08802     0
SJNORM050950_G1-TB-17-07027     0
SJNORM050951_G1-TB-17-07319     0
SJNORM050953_G1-TB-17-09516     0
SJNORM050954_G1-TB-17-09364     0
SJNORM050955_G1-TB-17-09805     0
SJNORM050957_G1-TB-17-06284     0
SJNORM055336_G1-TB-17-10401     0
SJNORM055337_G1-TB-17-10457     0
SJNORM055340_G1-TB-17-10888     0
SJNORM055341_G1-TB-17-07002     0
SJNORM055342_G1-TB-17-09177     0
SJNORM055344_G1-TB-17-03024     0
SJNORM055345_G1-TB-17-11801     0
SJNORM055346_G1-TB-17-11844     0
SJNORM055348_G1-TB-17-12273     0
SJNORM056701_G1-TB-17-08585     0
SJNORM056703_G1-TB-17-09469     0
SJNORM056704_G1-TB-17-09881     0
SJNORM056705_G1-TB-17-11194     0
SJNORM056706_G1-TB-17-12494     0
SJNORM056708_G1-TB-18-00316     0
SJNORM056709_G1-TB-18-00334     0
SJNORM056710_G1-TB-18-00335     0
SJNORM056713_G1-TB-17-08490     0
SJNORM056716_G1-TB-18-01201     0
SJNORM056717_G1-TB-18-01202     0
SJNORM056718_G1-TB-18-01204     0
SJNORM056719_G1-TB-18-01205     0
SJNORM056723_G1-TB-16-05131     0
SJNORM056724_G1-TB-17-08699     0
SJNORM056725_G1-TB-18-01758     0
SJNORM056726_G1-TB-18-01759     0
SJNORM056729_G1-TB-18-01835     0
SJNORM057621_G1-SC314910        0
SJNORM057622_G1-SC314911        0
SJNORM057623_G1-SC314912        0
SJNORM057624_G1-SC314913        0
SJNORM057625_G1-SC314914        0
SJNORM057626_G1-SC314915        0
SJNORM057628_G1-SC314917        0
SJNORM057629_G1-SC314918        0
SJNORM057630_G1-SC314919        0
SJNORM057631_G1-SC314920        0
SJNORM057632_G1-SC314923        0
SJNORM057633_G1-SC314924        0
SJNORM057635_G1-SC314929        0
SJNORM057636_G1-SC314930        0
SJNORM057638_G1-SC314932        0
SJNORM057639_G1-SC314933        0
SJNORM057640_G1-SC314934        0
SJNORM057641_G1-SC314935        0
SJNORM057642_G1-SC314936        0
SJNORM057643_G1-SC314937        0
SJNORM057644_G1-SC314938        0
SJNORM057645_G1-SC314939        0
SJNORM057646_G1-SC314940        0
SJNORM057647_G1-SC314941        0
SJNORM057648_G1-SC314942        0
SJNORM057649_G1-SC314943        0
SJNORM057650_G1-SC314944        0
SJNORM057651_G1-SC314945        0
SJNORM057652_G1-SC314946        0
SJNORM057654_G1-SC314948        0
SJNORM057656_G1-SC314950        0
SJNORM057657_G1-SC314952        0
SJNORM057659_G1-SC314954        0
SJNORM057660_G1-SC314955        0
SJNORM057662_G1-SC314957        0
SJNORM057663_G1-SC314958        0
SJNORM057665_G1-SC314962        0
SJNORM057666_G1-SC314963        0
SJNORM057667_G1-SC314964        0
SJNORM057668_G1-SC314965        0
SJNORM057669_G1-SC314966        0
SJNORM057670_G1-SC314967        0
SJNORM057671_G1-SC314968        0
SJNORM057672_G1-SC314969        0
SJNORM057673_G1-SC314970        0
SJNORM057674_G1-SC314971        0
SJNORM057675_G1-SC314972        0
SJNORM057676_G1-SC314973        0
SJNORM057678_G1-SC314975        0
SJNORM057679_G1-SC314976        0
SJNORM057680_G1-SC314977        0
SJNORM057681_G1-SC314978        0
SJNORM057682_G1-SC314979        0
SJNORM057683_G1-SC314980        0
SJNORM057684_G1-SC314981        0
SJNORM057686_G1-SC314983        0
SJNORM057687_G1-SC314984        0
SJNORM057688_G1-SC314985        0
SJNORM057689_G1-SC314986        0
SJNORM057690_G1-SC314987        0
SJNORM057691_G1-SC314988        0
SJNORM057692_G1-SC314989        0
SJNORM057693_G1-SC314990        0
SJNORM057694_G1-SC314991        0
SJNORM057695_G1-SC314992        0
SJNORM057696_G1-SC314993        0
SJNORM057697_G1-SC314994        0
SJNORM057698_G1-SC314995        0
SJNORM057699_G1-SC314996        0
SJNORM057700_G1-SC314997        0
SJNORM057701_G1-SC314998        0
SJNORM057702_G1-SC314999        0
SJNORM057703_G1-SC315000        0
SJNORM057704_G1-SC315001        0
SJNORM057705_G1-SC315002        0
SJNORM057706_G1-SC315003        0
SJNORM057707_G1-SC315004        0
SJNORM057708_G1-SC315005        0
SJNORM057709_G1-SC315006        0
SJNORM057710_G1-SC315007        0
SJNORM057711_G1-SC315008        0
SJNORM057712_G1-SC315009        0
SJNORM057713_G1-SC315010        0
SJNORM057714_G1-SC315011        0
SJNORM057715_G1-SC315012        0
SJNORM057716_G1-SC315013        0
SJNORM057719_G1-SC315016        0
SJNORM057720_G1-SC315017        0
SJNORM057722_G1-SC315019        0
SJNORM057723_G1-SC315020        0
SJNORM057724_G1-SC315021        0
SJNORM057725_G1-SC315022        0
SJNORM057726_G1-SC315023        0
SJNORM057727_G1-SC315024        0
SJNORM057728_G1-SC315025        0
SJNORM057731_G1-SC315028        0
SJNORM057732_G1-SC315029        0
SJNORM057733_G1-SC315030        0
SJNORM057734_G1-SC315031        0
SJNORM057735_G1-SC315032        0
SJNORM057736_G1-SC315033        0
SJNORM057738_G1-SC315035        0
SJNORM057739_G1-SC315036        0
SJNORM057741_G1-SC315038        0
SJNORM057742_G1-SC315039        0
SJNORM057765_G1-SB707997        0
SJNORM057787_G1-SC316748        0
SJNORM057788_G1-SC316749        0
SJNORM057789_G1-SC316750        0
SJNORM057790_G1-SC316751        0
SJNORM057791_G1-SC316752        0
SJNORM057792_G1-SC316753        0
SJNORM057793_G1-SC316754        0
SJNORM057794_G1-SC317461        0
SJNORM057795_G1-FF_9799_0251    0
SJNORM057796_G1-FF_9800_0249    0
SJNORM057797_G1-FF_1916_0252    0
SJNORM057798_G1-AE10097_0804    0
SJNORM057803_G1-FHS_009 0
SJNORM057804_G1-FHS_010 0
SJNORM057806_G1-FHS_020 0
SJNORM057807_G1-FHS_011 0
SJNORM057809_G1-FHS_026 0
SJNORM057810_G1-FHS_041 0
SJNORM057811_G1-FHS_042 0
SJNORM057812_G1-FHS_013 0
SJNORM057813_G1-FHS_040 0
SJNORM057814_G1-FHS_033 0
SJNORM057815_G1-FHS_034 0
SJNORM057817_G1-FHS_012 0
SJNORM057818_G1-FHS_008 0
SJNORM057819_G1-FHS_014 0
SJNORM057820_G1-FHS_030 0
SJNORM057821_G1-FHS_016 0
SJNORM057823_G1-FHS_015 0
SJNORM057824_G1-FHS_023 0
SJNORM057825_G1-FHS_017 0
SJNORM057827_G1-FHS_019 0
SJNORM057828_G1-FHS_031 0
SJNORM057829_G1-FHS_029 0
SJNORM057830_G1-FHS_038 0
SJNORM057832_G1-FHS_052 0
SJNORM057834_G1-FHS_067 0
SJNORM057835_G1-FHS_078 0
SJNORM057836_G1-FHS_072 0
SJNORM057838_G1-FHS_073 0
SJNORM057839_G1-FHS_055 0
SJNORM057840_G1-FHS_054 0
SJNORM057841_G1-FHS_069 0
SJNORM057844_G1-FHS_068 0
SJNORM057845_G1-FHS_060 0
SJNORM057846_G1-FHS_079 0
SJNORM057847_G1-FHS_059 0
SJNORM057848_G1-FHS_572 0
SJNORM057852_G1-FHS_120 0
SJNORM057853_G1-FHS_119 0
SJNORM057855_G1-FHS_253 0
SJNORM057856_G1-FHS_262 0
SJNORM057858_G1-FHS_294 0
SJNORM057861_G1-FHS_264 0
SJNORM057864_G1-FHS_384 0
SJNORM057866_G1-FHS_381 0
SJNORM057868_G1-FHS_379 0
SJNORM057869_G1-FHS_387 0
SJNORM057870_G1-FHS_472 0
SJNORM057871_G1-FHS_471 0
SJNORM057873_G1-FHS_508 0
SJNORM057874_G1-FHS_596 0
SJNORM057877_G1-FHS_507 0
SJNORM057878_G1-FHS_574 0
SJNORM057879_G1-FHS_575 0
SJNORM057883_G1-FHS_133 0
SJNORM057884_G1-FHS_130 0
SJNORM057885_G1-FHS_134 0
SJNORM057886_G1-FHS_136 0
SJNORM057888_G1-FHS_132 0
SJNORM057892_G1-FHS_606 0
SJNORM057893_G1-FHS_607 0
SJNORM057894_G1-TB-18-02819     0
SJNORM057896_G1-TB-18-03162     0
SJPRAD055343_G1-TB-17-09549     0
SJPSO057857_G1-FHS_272  0
SJRECA057822_G1-FHS_021 0
SJSBO057833_G1-FHS_056  0
SJTALL055339_G1-TB-17-10889     0
SJTESCA057843_G1-FHS_076        0
SJTHCA050956_G1-TB-17-09467     0
slivar version: 0.1.2

**Comment by brentp** [comment]
I think this has been resolved, please re-open if that is not the case.
