### ISSUE TITLE
gnomAD v3 hg38 file

### ISSUE THREAD

**Issue by nroak** [brentp/slivar#45]
Brent, are you currently working on processing the new gnomAD released v3 (hg38 native) for >60K genomes to be compatible with Slivar? 
If not, I will be happy to process and provide it here. I will use the make gnotate script per Wiki or feel free to share the command if you already have one for gnomAD.
https://gnomad.broadinstitute.org/downloads

**Comment by brentp** [comment]
this is out in new release.
