### ISSUE TITLE
Add Gnotate to the latest docker image

### ISSUE THREAD

**Issue by cvlvxi** [brentp/slivar#5]
Hi Brent,

I've been interested in using gnotate and the docker image you linked: https://cloud.docker.com/repository/docker/brentp/slivar but I noticed this subcommand isn't available at the moment. Is this something that can be added easily?

Cheers!

**Comment by brentp** [comment]
I hadn't noticed this, must have forgot to update it. I'll make one for the next release which will be out this week.

You can also build yourself using choosenim or following the Dockerfile in this repo.

**Comment by brentp** [comment]
`brentp/slivar:v0.0.5` is now available on dockerhub. Please let me know any questions/problems.
