### ISSUE TITLE
Removing gnomad AC0 flag variants

### ISSUE THREAD

**Issue by syouligan** [brentp/slivar#59]
Hi Brent

I just wanted to alert you to a potential issue I have found recently when screening rare disease patients as the problematic parameter is also apart of your pipeline (according to one of your blog posts).

I have been running slivar with a filter that removed variants that didnt have a "PASS" flag in the gnomad v2.1 VCF (similar to your standard pipeline). One of the flags which can occur is the "AC0" flag - tripped when a variant is not found in the gnomad cohort. Removing these variants may be counter productive in the rare disease context as we may expect these variants to not be seen in the general healthy population. Indeed this removed an established disease causing variant that had been identified by a previous targeted molecular analysis. Had it not been for this positive control case we may not have realised the "AC0" flag was removing potential variants of interest.

You may already be on to this but I thought I should share incase.

Thanks for your work.

Scott

**Comment by brentp** [comment]
wow. thanks for letting me know. 
AC0 variants are "`Allele count is zero after filtering out low-confidence genotypes (GQ < 20; DP < 10; and AB < 0.2 for het calls)`". I would still be very skeptical of those, but it could happen that they are real in your cohort. Could you share (offline if needed) the site where this occurred? I'd like to have a look in order to decide what to do about this.
I am also interested in the targeted molecular analysis, if you can share more about that.

**Comment by syouligan** [comment]
The exact SNP is this one https://gnomad.broadinstitute.org/variant/4-1806119-G-A. Its known to a rare skeletal dysplasia called Achondroplasia. The clinician scientist that diagnosed the patient with this disease called for targeted sequencing of this specific gene (genomic technically, not molecular, sorry for the confusion). As the patient is presenting with other skeletal characteristics atypical for this condition, they were sent for whole genome sequencing as well. When we couldn't find the previously confirmed mutation we started digging into why and I found this. I was thinking of writing a feature to keep either pass or AC0 and retain the flag so I know which variants are which. I also found it pretty alarming and though I should share haha. Thanks for your help and would be very greatful for your thoughts on this.

**Comment by brentp** [comment]
thank you. this is helpful. I had forgotten, but it looks like the [latest recommended filters for rare disease](https://github.com/brentp/slivar/wiki/rare-disease) do not exclude variants that are non-PASS in gnomad. At one point, it did, but if you update to the latest, then that variant should not be filtered.

the [slivar tsv output](https://github.com/brentp/slivar/wiki/tsv:-creating-a-spreadsheet-from-a-filtered-VCF) recommends having that in the extracted fields, so it would be apparent, so I think this current (updated) approach is best.

**Comment by syouligan** [comment]
Ah good stuff, thought you might be across it. I'll get on to it. Thanks mate
