### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by nroak** [brentp/slivar#6]
This looks very helpful. I would like to implement this to do a quick analysis on some families using the examples in the readme file.
I needed some help with installation, however.

I followed the link, https://github.com/brentp/slivar#installation -> https://github.com/brentp/slivar/releases/tag/v0.0.5 and downloaded the source code.

I am clueless about how to proceed from there to install the tool?
I did `cd slivar-0.0.5/`. What next?

**Comment by brentp** [comment]
hi, you downloaded the source, just download the binary instead from here: https://github.com/brentp/slivar/releases/download/v0.0.5/slivar

it's a link on the same page.

**Comment by brentp** [comment]
is this working for you?

**Comment by nroak** [comment]
Thanks for checking, Brent. When I ran slivar binary, I got the error below.
`could not load: libhts.so
compile with -d:nimDebugDlOpen for more information`
I guessed I have to setup NIM environment but couldn't successfully do it.

**Comment by brentp** [comment]
libhts.so is from htslib, you will need to have that build/installed. You can use `export LD_LIBRARY_PATH=/directory/containing/` to get it to work. That is not a nim error.

**Comment by nroak** [comment]
Perfect, that got it to work. I will test out with a variant file now.
I ran two commands, 
`find ~ -name libhts.so`
`LD_LIBRARY_PATH=/directory/containing/`

On an separate note, can it work with trios as well as quads and larger families?

**Comment by brentp** [comment]
yes, it works with trios just by specifying a --ped file. for other things, you'll need to specify an --alias file and a groups expr. See: https://github.com/brentp/slivar/#groups

I'll document this more thoroughly before the next release, but that should get you started.
