### ISSUE TITLE
Suppress PED Samples Dump

### ISSUE THREAD

**Issue by achtungmike** [brentp/slivar#61]
It would be great if there was an option to suppress slivar from dumping out all of the samples listed in the PED file that are not in the samples file.  I'm running trio VCF files independently and slivar will dump a huge list of sample names to the terminal creating a lot of noise.

I was looking through the code to see if I could implement something and submit a PR, but it looks like you already have a verbosity or quiet mode implemented.

`let verbose=getEnv("SLIVAR_QUIET") == ""`

But there doesn't seem to be a command line argument to set this, and I don't understand what the "getEnv" function does in Nim and where it's pulling environmental variables from, the OS?  I tried defining a Bash variable named SLIVAR_QUIET and set it to "True",  but that didn't seem to work.

The exact message is "sample name, sample name, sample name,...not found in VCF samples".  I found that phrase "not found in VCF samples" in your pedfile library.

https://github.com/brentp/pedfile/blob/b5e322bf51c024404bc7d73b46fe3a62d37187a0/src/pedfile.nim#L264

**Comment by brentp** [comment]
you should just be able to do:
```
export SLIVAR_QUIET=yes
slivar expr ...
```
and the messages will not appear.

**Comment by achtungmike** [comment]
Unfortunately, I set SILVAR_QUITE to true instead of SILVAR_QUIET.  So with that fixed it works well.  It doesn't look like I can edit your wiki, but it might be good to document that as it's very helpful.  Awesome program overall though, it's making my job much easier! Thanks!
