### ISSUE TITLE
How to ignore missing field?

### ISSUE THREAD

**Issue by weizhu365** [brentp/slivar#63]
Dear sliver developer;

I am trying to use slivar on a VCF file which is a merged variant call from GATK and freebayes.  Therefore, some INFO fields are not available for every variant as expected.  I am trying to filter the VCF file using sliver as below:
```
sliver expr --pass-only --vcf chr21.vcf.gz  --out-vcf annotated.bcf --info "variant.call_rate > 0.9 & INFO.VAK_gatk4_AN>0"
> slivar version: 0.1.11 5d6a5990fc06b52cbb1930806d03f786cf27d267
[slivar] 1255 samples matched in VCF and PED to be evaluated
[slivar] error evaluating info expression (this can happen if a field is missing):
error from duktape: unknown attribute:VAK_gatk4_AN for expression:variant.call_rate > 0.9 & INFO.VAK_gatk4_AN>0

[slivar] error evaluating info expression (this can happen if a field is missing):
error from duktape: unknown attribute:VAK_gatk4_AN for expression:variant.call_rate > 0.9 & INFO.VAK_gatk4_AN>0

[slivar] error evaluating info expression (this can happen if a field is missing):
error from duktape: unknown attribute:VAK_gatk4_AN for expression:variant.call_rate > 0.9 & INFO.VAK_gatk4_AN>0
...
```

Is there any way to turn off the error messages from slivar and process vcf file as I wanted? 

Thanks,

Wei

**Comment by brentp** [comment]
you can do: ` --info "variant.call_rate > 0.9 && ('VAK_gatk4_AN' in INFO) && INFO.VAK_gatk4_AN>0"` (and adjust that to the exact logic that you need).
note that you should use &&, not &. the latter is bitwise and which is not what you want.

**Comment by weizhu365** [comment]
I noticed that && issue and also thank your for the tips.  By the way, I noticed there is difference in the filtered results between bcftools and Silver. I hope that the difference will be removed after applying your trick.  

Best regards,

Wei
