### ISSUE TITLE
Add "AC_male" (v2 and v3) and "controls_AC_male" (v2) to gnomAD gnotate files for chrX

### ISSUE THREAD

**Issue by seboyden** [brentp/slivar#64]
Enable filtering on male hemizygote count in gnomAD for X-linked variants

**Comment by JohannKaspar** [comment]
This would be very helpful indeed!

**Comment by seboyden** [comment]
I ran ```make-gnotate``` myself on the chrX VCFs for gnomad v2 and v3 to do this.  Future releases of pre-made gnotate files will be on newer versions of gnomad anyway.
