### ISSUE TITLE
Low complexity region bed file?

### ISSUE THREAD

**Issue by jpdna** [brentp/slivar#66]
Hi Brent,

slivar look really great!
In your related paper on BioRxiv, you mention excluding low complexity regions.
Can you point to a BED file you recommend for GRCh38 and 37 identifying such region?
And - should that that region filter be applied before slivar - or is there a way to integrate it in the slivar command?
Thanks!

**Comment by brentp** [comment]
Hi, the files are here: https://github.com/lh3/varcmp/tree/master/scripts
make sure to get the raw files (e.g.: https://github.com/lh3/varcmp/raw/master/scripts/LCR-hs37d5.bed.gz),
not the html files.
If you run `slivar expr`, it will show the help. You can send that file to the `--exclude` argument.
