### ISSUE TITLE
Rare disease example link (not big issue), gnomad v3

### ISSUE THREAD

**Issue by Phillip-a-richmond** [brentp/slivar#72]
In your rare disease example the gff3 link you provide is deprecated if using GRCh38.

https://github.com/brentp/slivar/wiki/rare-disease

Here's a path you can replace it with:

ftp://ftp.ensembl.org/pub/release-96/gff3/homo_sapiens/Homo_sapiens.GRCh38.96.gff3.gz

Also...
Do you have plans to provide the compressed annotation for gnomAD v3 natively mapped to GRCh38?

Cheers,
Phil

**Comment by brentp** [comment]
Hi, I updated the wiki to include gff links for hg38 and grch37.
the gnomad hg38 zip is here: https://slivar.s3.amazonaws.com/gnomad.hg38.genomes.v3.fix.zip
that is linked from every release. i'll update the readme to include it as well.
