### ISSUE TITLE
pslivar through bioconda

### ISSUE THREAD

**Issue by williamrowell** [brentp/slivar#73]
Would it be possible to add pslivar to the bioconda recipe for slivar?

**Comment by williamrowell** [comment]
I'd be happy to create a PR to add `pslivar` to the `slivar` bioconda recipe, but it doesn't appear there is a matching version of `pslivar` for the current release.

**Comment by brentp** [comment]
hi, sorry for delay. 
i added the (same) pslivar binary to latest release. it'd be great if you added it to the bioconda recipe.

**Comment by williamrowell** [comment]
Thanks for the update.  Submitted a PR on bioconda-recipes.
