### ISSUE TITLE
AD: int32 required to use this tool

### ISSUE THREAD

**Issue by sprakashUTH** [brentp/slivar#83]
I receive this error when I use slivar: "AD: int32 required to use this tool." What should I do to fix?

**Comment by brentp** [comment]
you should be able to use without that field and just get a warning. Are you talking about `duodel`?
AD is a field that indicates the number of reference and alternate reads for each sample at each site and is required for duodel.
You may be able to create it from other fields if the VCF lists reference and alt reads in some other way.
