### ISSUE TITLE
Errors reported by slivar and no variants

### ISSUE THREAD

**Issue by sprakashUTH** [brentp/slivar#85]
Hi! I tested slivar by filtering for variants that are in cases but not in unaffected samples. This command ran without errors except for the two below, but returned 0 variants. What am I doing wrong?

Command:
./slivar expr --vcf $vcf --ped $ped --pass-only -g $gnomad --info 'INFO.impactful && INFO.gnomad_popmax_af < 0.01 && variant.FILTER == "PASS" && variant.ALT[0] != "*"' --family-expr 'aff_only:fam.every(function(s) {s.het==s.affected && s.hom_ref==!s.affected && s.GQ>5})' --js slivar-functions.js | bcftools csq -s - --ncsq 40 -g $gff -l -f $fasta - -o $WORK/uwbatches2-4/affected.vcf

error: unknown impact "non_canonical_start_codon" from csq "G|initiator_codon_variant&non_canonical_start_codon|LOW|C5orf60|ENSG00000204661|transcript|ENST00000513845|nonsense_mediated_decay|1/4|c.1T>C|p.Leu1?|3/771|1/243|1/80||" please report the variant at https://github.com/brentp/slivar/issues
error: unknown impact "non_canonical_start_codon" from csq "C|initiator_codon_variant&non_canonical_start_codon|LOW|VPS13A|ENSG00000197969|transcript|ENST00000467124|protein_coding|1/3|c.1T>C|p.Leu1?|3/324|1/123|1/40||" please report the variant at https://github.com/brentp/slivar/issues

**Comment by brentp** [comment]
The fix for this is in master and out in next release
