### ISSUE TITLE
Using groups with multiple samples results in error

### ISSUE THREAD

**Issue by edg1983** [brentp/slivar#88]
Hi, 
I have a multi-sample VCF containing 2 groups of individuals: highrisk and lowrisk.
I want to annotate variants that are present in highrisk samples and absent from lowrisk ones.

To do so I've prepared a groups.txt file as follows:
```
#lowrisk        highrisk
T10945,T10926,T11258,T10965     T10967,T10947,T10940
```

Then, following the example in group wiki, I've prepared the following functions.js file:
```
function proportion_with_alt(samples) {
    var n = 0
    for(i=0; i < samples.length; i++){
      if(samples[i].alts == 1 || samples[i].alts == 2 && samples[i].GQ >=10){
          n += 1
      }
    }
    return n / samples.length
}

function proportion_with_ref(samples) {
    var n = 0
    for(i=0; i < samples.length; i++){
      if(samples[i].alts == 0 && samples[i].AB < 0.01 && samples[i].GQ >=10){
          n += 1
      }
    }
    return n / samples.length
}
```

However, when I try to run the slivar command (slivar v.0.2.1):
```
slivar expr --vcf input.vcf.gz --js functions.js --alias groups.txt --pass-only --skip-non-variable --group-expr "highonly:proportion_with_alt(highrisk) == 1 && proportion_with_ref(lowrisk) == 1"
```

I got this error, complaining that multiple samples are present in column 0, which is exactly what I want and I suppose this should work based on your wiki example for groups - multi-generational pedigree
```
Error: unhandled exception: slivar/groups:got > 1 sample in line T10945,T10926,T11258,T10965    T10967,T10947,T10940, column 0. @[Sample(id:T10945, i:0, affected:false, dad: "", mom: ""), Sample(id:T10926, i:8, affected:false, dad: "", mom: ""), Sample(id:T11258, i:9, affected:false, dad: "", mom: ""), Sample(id:T10965, i:14, affected:false, dad: "", mom: "")] [ValueError]
```

Thanks for support!

**Comment by brentp** [comment]
Hi, glad you're trying out the groups. 
Columns labels with multiple samples must end in 's'. So you can use:
```
#lowrisks        highrisks
T10945,T10926,T11258,T10965     T10967,T10947,T10940
```
(note lowrisks instead of lowrisk and same for highrisks).

I'll improve this error message to give more help.
let me know any more questions.

**Comment by edg1983** [comment]
Great thanks! I completely missed the "s" was mandatory in column names.

I want also to report a couple of minor issues:

**Comment by brentp** [comment]
I updated the error message to be more informative.
For 1. I see what you mean. That is a big confusing. You did see something like: `[slivar] writing final summary file to ... ` at the end of the run, right? I'll think about how to improve the output here. It was really to give an idea of how fast things are going but it's only reported for the first thread.

For 2. This was reported and will be out in next release. (see f55286a)

Thanks for reporting all of these.

**Comment by edg1983** [comment]
No problem!
One last question. Which is the best approach to extract variants using `slivar tsv` after the above analysis with group expression.

**Comment by brentp** [comment]
slivar tsv currently only works on trios. I'll open a new issue for that. It could indeed be useful to expand it.
