### ISSUE TITLE
recessive_func

### ISSUE THREAD

**Issue by snashraf** [brentp/slivar#9]
Hi Brent,

Thanks again for wonderful tool.

I was trying to use this part. 
"recessive:recessive_func(kid, mom, dad)"
and I am getting some error. I am just wondering if I have to load this recessive_func from somewhere? Could you please provide an example scripts for that? Maybe you can think about the dominant condition as well?

**Comment by brentp** [comment]
Hi, that was an example. it's not actually implemented yet. After the release that's pending, I plan to write functions like this. 
It might look like:
```Javascript
function recessive_func(kid, mom, dad) {
  // assume kid.affected
  return  kid.alts == 2 && (mom.affected == mom.alts == 2) \
    && (dad.alts == 2 == dad.affected) 
  // and other checks for depth and allele balance.
}

Then, that can be added to the javascript file passed to `--load`.

**Comment by snashraf** [comment]
OK !! So  I will wait for the next release!!

**Comment by brentp** [comment]
you can certianly wait for release, but you can write your own functions, that's the point of this library--that it's easy to write your own.

**Comment by snashraf** [comment]
yes that true !! 

I am NOT able to use --load function with above javascript.

function recessive_func(kid, mom, dad) {
  //assume kid.affected
     return  kid.alts == 2 && (mom.affected == mom.alts == 2) \
        && (dad.alts == 2 == dad.affected)
           }

**Comment by brentp** [comment]
--load is a path to a file. you'll have to put that code into a file. if that's not the problem, you'll have to be more specific as to the problem you are encountering.

**Comment by snashraf** [comment]
Here is my exact command.

slivar expr --pass-only --vcf fam1.vcf.gz --ped fam1.ped --load funcation.js --info "variant.call_rate > 0.9" --trio "denovo:kid.alts == 1 && mom.alts == 0 && dad.alts == 0  && kid.AB > 0.25 && kid.AB < 0.75 && (mom.AD[1] + dad.AD[1]) == 0 && kid.GQ >= 20 && mom.GQ >= 20 && dad.GQ >= 20 && kid.DP >= 12 && mom.DP >= 12 && dad.DP >= 12" --trio "informative:kid.GQ > 20 && dad.GQ > 20 && mom.GQ > 20 && kid.alts == 1 && ((mom.alts == 1 && dad.alts == 0) || (mom.alts == 0 && dad.alts == 1))" --trio "recessive:recessive_func(kid, mom, dad)" --out name.vcf

slivar version: 0.0.5
Usage: slivar expr [options --pass-only --out-vcf <path> --vcf <path> --ped <path> --trio=<expression>... --group-expr=<expression>... --info=<expression>]

My function.js file is below. 

function recessive_func(kid, mom, dad) {
//assume kid.affected
return kid.alts == 2 && (mom.affected == mom.alts == 2) 
&& (dad.alts == 2 == dad.affected)
}

Am i missing something ?

**Comment by brentp** [comment]
my apologies. it should be `--js functions.js`

**Comment by brentp** [comment]
you can see the full help by running `slivar expr --help`

**Comment by snashraf** [comment]
Thanks !! It worked now .

**Comment by snashraf** [comment]
Hi Brent

I was using below function from javascript that you updated recently. 
function trio_autosomal_dominant(kid, dad, mom) {
                                        // affected samples must be het.
                                            if(!(kid.affected == (kid.alts == 1) && mom.affected == (mom.alts == 1) && dad.affected == (dad.alts == 1))) { return false; }
                                                 if(kid.DP < 7 || mom.DP < 7 || dad.DP < 7) { return false; }
                                                     return kid.affected
                                                     }

I am getting same variants are being tagged as both denovo and Dominant, while I dont have any affected parents in my trio.
Could you please check this once?

Thanks

**Comment by brentp** [comment]
well, that makes sense. the de novo function is finding an autosomal dominant variant. you can get only variants+trios where one parent is affected by changing the AD function to:
```
function trio_autosomal_dominant(kid, dad, mom) {
    // affected samples must be het.
    if(!(kid.affected == (kid.alts == 1) && mom.affected == (mom.alts == 1) && dad.affected == (dad.alts == 1))) { return false; }
    if(kid.DP < 7 || mom.DP < 7 || dad.DP < 7) { return false; }
    return kid.affected && (mom.affected != dad.affected) // change here.
}
```
