### ISSUE TITLE
Link for gene_description returns 404

### ISSUE THREAD

**Issue by wdecoster** [brentp/slivar#91]
Hi Brent,

Just wanted to let you know that the link for a gene description file (in slivar tsv; http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype.txt) returns a 404.

Cheers,
Wouter

**Comment by brentp** [comment]
fixed, thanks for reporting. will be out in next release, likely next week.
