### ISSUE TITLE
Issue using adjusted impactful txt

### ISSUE THREAD

**Issue by team-tomato-salad** [brentp/slivar#97]
Hi,

I tried to use INFO.impactful with an adjusted list of variants on VEP/CSQ annotations . And I got an error: 

> [slivar] warning! no IMPACTFUL_CUTOFF specified. INFO.impactful will not be useful

I made sure that I exported the correct path to the adjustes-order.txt. And here is an example of the CSQ header line from my vcf. 

> ##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position 

I am wondering why the Slivar isn't reading my txt and if there's a way to work around that. 

Thank you!

**Comment by brentp** [comment]
Hi, thanks for reporting.
There was a bug where it was actually not possible to use your own ordering with `SLIVAR_IMPACTFUL_ORDER` environment variable. I have just fixed that. 
You can use the default ordering by using `unset SLIVAR_IMPACTFUL_ORDER` before running slivar. The fix so you can customize will be out later this week and you can also use this static binary.
[slivar.gz](https://github.com/brentp/slivar/files/6900860/slivar.gz)
