### ISSUE TITLE
Data driven cutoffs

### ISSUE THREAD

**Issue by Madelinehazel** [brentp/slivar#98]
Hi Brent, 

Thanks for this excellent tool! Is it possible to explore data driven cutoffs for SVs? I'm trying to look at some info and format fields for SVs called by Manta in a trio using the following command:

`slivar ddc \
    --chrom "chr15" \
    --info-fields 'MATE_BND_DEPTH,BND_DEPTH' \
    --fmt-fields 'SR,PR' $vcf $ped`

However, I get the following output from slivar, and the html file was not populated:
`slivar version: 0.1.11 5d6a5990fc06b52cbb1930806d03f786cf27d267
[slivar] wrote output to:slivar-ddc.html
number of infos:0
trio:0`

So the info fields, and the trio structure, don't seem to be picked up. I also tried the following command using the GATK Haplotype caller SNVs and indel vcf for the same trio:

`slivar ddc \
    --chrom "chr15" \
    --info-fields 'MQ,DP,FS' \
    --fmt-fields 'GQ' $vcf $ped`

and similarly had the following output:
`> slivar version: 0.1.11 5d6a5990fc06b52cbb1930806d03f786cf27d267
[slivar] wrote output to:slivar-ddc.html
number of infos:0
trio:0`

Would appreciate your insight on the issue! Thanks, Madeline.

**Comment by brentp** [comment]
Hi, this looks like you don't have the trios specified correctly in your pedigree file. Can you show a full trio output in your $ped?
Also, are you sure you have `chr15` and not `15`?

**Comment by Madelinehazel** [comment]
Thanks for the quick reply! The ped looks like this:

1159R	1159R_CH0531	1159R_CH0880	1159R_CH0879	2	2
1159R	1159R_CH0879	0	0	2	-9
1159R	1159R_CH0880	0	0	1	-9

I did try both 15 and chr15, and neither seemed to work unfortunately!

**Comment by brentp** [comment]
you have a very old version of slivar, try to update to `v0.2.5`, then if it's still broken, let's debug further.

**Comment by Madelinehazel** [comment]
Ahh of course, thanks! Working now.

**Comment by brentp** [comment]
glad to hear it.
