### ISSUE TITLE
make-genotate genomes files 

### ISSUE THREAD

**Issue by skanwal** [brentp/slivar#99]
Hello @brentp 

Firstly, thanks for this resource. 

To provide context, I have a tumour-only VCF for a cancer sample that I'd like to filter out for likely false variants.
I am exploring slivar to see if we can leverage population frequency to help with noise reduction in sample VCF. 

Reading through [wiki](https://github.com/brentp/slivar/wiki/gnotate#creating-gnotate-files), I wanted to ask the best way to get `gnomad.genomes.r2.1.sites.chr*.vcf.bgz`. Looking through the [gnomad website](https://gnomad.broadinstitute.org/downloads#v3-variants), noticed there are quite huge individual files for all chromosomes (v3.1 as I am working with genome build 38). Do we need to download these for creating custom gnotate files? 

**UPDATE**: Noted slivar comes with [gnomad files for hg38](https://github.com/brentp/slivar#gnotation-files) - giving these a try with my sample VCF for filtering variants.

Help will be appreciated.
Thanks.

**Comment by brentp** [comment]
Hi, let me know if you need further help, you should be able to use the provided zip files for hg38, but yes, if you want to make your own gnotate zip files you'll need to download all of the gnome vcfs.

**Comment by skanwal** [comment]
Thank you. Closing this for now as I was able to to use the provided gnomad files.
